import { MapDetail } from '@/types';

export const mapsData: MapDetail[] = [
  {
    id: 'dust2',
    name: 'Dust2',
    image: '/maps/dust2-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description:
      'Dust 2 es un mapa A o B. Si no están en medio → están atacando una punta. Fondo es el espacio más importante de A. Oscuro bajo es el choke clave de B. Medio (Xbox/corredor) conecta ambos sites y da info crítica a los CT. Lo más importante es no morir en el default.',
    sideFavor: 'Balanced',
    callouts: {
      siteA: ['Largo', 'Fondo A', 'Fosa', 'Azul', 'Casa de fondo', 'Esquina', 'Rampa'],
      siteB: ['Túnel', 'Oscuro bajo', 'Oscuro alto', 'Side B', 'Auto', 'Carro', 'Altar', 'Rampa B'],
      middle: ['Xbox', 'Doble puerta', 'Corto', 'Ventana CT', 'Corredor', 'Barriles', 'Caja gorda'],
    },
    fundamentals: {
      t: [
        'No morir en el default es LO MÁS IMPORTANTE de terror en Dust 2.',
        'Setup 3-2: 3 hacia A (fondo/largo) + 2 hacia B (túnel/oscuro)',
        'Lurker fondo: juega lento, corta rotación, se suma al grupo según jugada',
        'Llegar shifteando a fondo sin que te vean = ronda ganada',
      ],
      ct: [
        'Siempre dominar FONDO o BARANDA. No perder las dos nunca.',
        'Ancla B nunca rota sin información clara — B es muy difícil de retakear',
        'Rotador con util siempre: Hi gorda es clave al venir medio',
        'El ancla B no puede morir en rush B — jamás.',
      ],
    },
    strats: [
      {
        id: 'd2-pistol-t-1',
        name: 'G2: Split Baranda + Fondo',
        type: 'pistol',
        team: 'T',
        description: '2 ganan baranda · 3 por fondo · Smoke puerta + Moli baranda',
        setup: '2 baranda · 3 fondo en punto máximo',
        utilities: ['Smoke puerta', 'Molotov baranda', 'Flash x2'],
        tips: [
          'Uno compra smoke + moli. Moli a baranda (estructura) + smoke puerta',
          '2 jugadores ganan baranda cuando está activa la moli',
          'El primero de fondo hace straf (lleva la mira) → los otros 2 tradean',
        ],
      },
      {
        id: 'd2-pistol-t-2',
        name: 'Rush B (túnel)',
        type: 'pistol',
        team: 'T',
        description: '5 por túnel · Flash x2 entry + smoke puerta',
        setup: '5 por túnel',
        utilities: ['Flash x2 entry', 'Smoke puerta'],
        tips: [
          'Respawn 3 (CLAVE): smoke puerta corriendo + dos flashes desde la mancha',
          'Objetivo: smoke puerta activa + CT flasheado = entrar limpio y matar ancla',
          'Si el respawn 3 no tira bien las latas, el rush pierde. Práctica obligatoria.',
        ],
      },
      {
        id: 'd2-pistol-ct-1',
        name: 'Mongols: 1-1-1-2B (Duals)',
        type: 'pistol',
        team: 'CT',
        description: '1 fondo · 1 baranda (FB+HE) · 1 oscuro bajo (Duals) · 2 en B',
        setup: '1-1-1-2 distribuido',
        utilities: ['Duals', 'FB', 'HE'],
        tips: [
          'Jugador Duals: se mete oscuro bajo pegado a caja — letal a corta distancia',
          '2 de B: anti + se pegan a boca oscuro al timing — pullean con el de oscuro',
          'Dropear buenas duals a jugador habilidoso. El ancla oscuro tiene que brillar.',
        ],
      },
      {
        id: 'd2-buy-t-1',
        name: 'Exec Baranda (Pain Style)',
        type: 'buy',
        team: 'T',
        description: 'Doble smoke baranda + combo NK (smoke caja + moli + flash x2)',
        setup: '4-5 comprando completo',
        utilities: ['Doble smoke baranda', 'Molotov', 'Flash x2'],
        tips: [
          'Smoke 1 (David): agachado escalera, apunta ventana abajo izquierda',
          'Smoke 2 (NK caja): agachado, puntito blanco, se choca con caja',
          'Entry fragers entran mirando UN ángulo solo',
          'Lo que NO puede faltar: doble smoke + combo NK. Todo lo demás es bonus.',
        ],
      },
      {
        id: 'd2-buy-t-2',
        name: 'Split Medio-B (Spirit)',
        type: 'buy',
        team: 'T',
        description: '2-3 por medio → B · 2 por oscuro bajo (juro) coordinados',
        setup: 'Split con entrada por Medio',
        utilities: ['Smoke CT caja gorda', 'Molotov x2', 'Flash'],
        tips: [
          'La smoke de caja gorda es la más importante — sin ella el CT los mata a todos',
          'Los de oscuro: moli caja gorda + moli fondo altar',
          'Los de oscuro calan info → si no hay nadie → se mandan limpiando ángulos',
        ],
      },
      {
        id: 'd2-buy-t-3',
        name: 'Rush A largo (Vitality)',
        type: 'buy',
        team: 'T',
        description: 'Solo 1 jugador tira toda la util. 5 rushean largo.',
        setup: '1 tira util · 5 rushean',
        utilities: ['Smoke esquina largo', 'Flash x2', 'Molotov'],
        tips: [
          'Un solo jugador tira TODO. Los demás solo corren y matan.',
          'Flash ancha temprana (para el que tira util antiflash)',
          'Moli detrás del humo (para reagresión CT)',
          'Muy eficiente en pug.',
        ],
      },
      {
        id: 'd2-eco-t-1',
        name: 'Rush B (5 túnel)',
        type: 'eco',
        team: 'T',
        description: '5 por túnel sin demorarse',
        utilities: ['Smoke puerta', 'Flash x2'],
        tips: [
          'Respawn 3 smokea puerta corriendo (CLAVE)',
          'Respawn 1+2 flashean al CT de entrada',
          'Objetivo: matar ancla + robar rifle',
          'Sin smoke puerta el rush no sale.',
        ],
      },
      {
        id: 'd2-eco-t-2',
        name: 'Default pasivo',
        type: 'eco',
        team: 'T',
        description: 'Uno en cada zona → buscar picks',
        utilities: [],
        tips: [
          'No atacar sin util — esperar errores',
          'Si roban rifle → atacar esa zona',
          'Lurker fondo: presionar, no morir',
          'Usar tiempo. CT impaciente = pick gratis.',
        ],
      },
      {
        id: 'd2-force-t-1',
        name: 'SMG rush B',
        type: 'force',
        team: 'T',
        description: 'Rush B con Mac-10 / SMG',
        setup: '5 rushean con SMG',
        utilities: ['Smoke puerta', 'Flash x2'],
        tips: [
          'Al menos smoke puerta corriendo',
          'Flash x2 entry — sorprender al CT',
          'Plantar y jugar postplant',
          'Ventaja: CT guarda para próxima ronda.',
        ],
      },
      {
        id: 'd2-force-t-2',
        name: 'Split largo+corto',
        type: 'force',
        team: 'T',
        description: '3 largo + 2 corto/medio → split A',
        setup: 'Split A',
        utilities: ['1 smoke esquina largo'],
        tips: [
          'Sin exec completo: explotar rapido',
          'Si tienen 1 smoke → esquina largo',
          'Timing: ambos grupos colapsan juntos',
          'Prioridad: matar AP y robar arma.',
        ],
      },
    ],
  },
  {
    id: 'mirage',
    name: 'Mirage',
    image: '/maps/mirage-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description:
      'Quien controla medio controla el mapa. Mid → Connector abre A; Short abre B. Los T necesitan obtener control de medio para decidir el flujo de la ronda.',
    sideFavor: 'CT-sided',
    callouts: {
      siteA: ['Ramp', 'Palacio', 'Tetris', 'Sándwich', 'CT', 'Jungla', 'Banco', 'Cabeciña'],
      siteB: ['Apps', 'Van', 'Bench', 'Pillar', 'Default B', 'Market', 'Short'],
      middle: ['Top Mid', 'Window', 'Connector (short)', 'Underpass (L)', 'Moscú', 'Liga'],
    },
    fundamentals: {
      t: [
        'Controlar medio es CLAVE: Mid → Connector abre A; Short abre B',
        'Split A: 3 Liga · 1 Caverna (lateo) · 1 Palacio (cover)',
        'Los 3 de liga NO van juntos — 1 lleva arma, 2 saltan. Moverse = difícil de matar',
      ],
      ct: [
        'Setup base 2-1-2: A anchor (Ticket/CT) + Mid (Window+DL) + B anchor (Van/Bench)',
        'Buda, DL y Liga: comunicación constante. Ellos marcan el rumbo de la ronda',
        'Moli Carroza temprano para negar salida medio',
      ],
    },
    strats: [
      {
        id: 'mirage-pistol-t-1',
        name: 'Liquid Split A',
        type: 'pistol',
        team: 'T',
        description: '3 Liga · 1 Caverna (lateo) · 1 Palacio (cover)',
        setup: '3-1-1 Liga/Caverna/Palacio',
        utilities: ['Smoke Triple (bugada)', 'Smoke Jungla'],
        tips: [
          '3 corren Liga con Glock — saltando, moviéndose siempre',
          'Caverna tira smokes, latea en liga',
          'Si matan 1-2 → intentar comer site. Si no → mantener posición',
        ],
      },
      {
        id: 'mirage-pistol-t-2',
        name: 'Rush B',
        type: 'pistol',
        team: 'T',
        description: '5 por Apps · Smokes Market Window + Market Door',
        setup: '5 Apps',
        utilities: ['Smoke Market Window', 'Smoke Market Door'],
        tips: [
          'Un jugador tira ambas smokes desde corner TV room',
          'Todos van Apps sin demorarse nada',
          'Entran pegados por Van y Bench',
          'Funciona anti-eco CT o cuando sospechan stack A. El momentum lo es todo.',
        ],
      },
      {
        id: 'mirage-buy-t-1',
        name: 'Full Exec A (FaZe)',
        type: 'buy',
        team: 'T',
        description: '4 Caverna · 1 Palacio · smokes completas',
        setup: '4-1 Caverna/Palacio',
        utilities: ['Smoke Cabeciña', 'Smoke Banco', 'Smoke CT', 'Molotov x2'],
        tips: [
          'Rein: smoke Cabeciña (doble click Jantrow) + Banco',
          'Brocky: smoke CT + flash LARGA que fea CT',
          'Entry fragers van PEGADOS a smokes — no salen de una',
          'Carrigan NO se expone para el humo hasta que esté todo clear',
        ],
      },
      {
        id: 'mirage-buy-t-2',
        name: 'Split LB (NaVi)',
        type: 'buy',
        team: 'T',
        description: '2 por Medio → L · 3 por B → colapso simultáneo',
        setup: '2 Mid + 3 B',
        utilities: ['Smoke Buda (respawn)', 'Smoke Liga (rápida)', 'Smoke Pasaje (opcional)'],
        tips: [
          '2 de medio dominan Mid → matan → se mandan para L',
          '3 de B llegan a punto máximo (Van) y esperan el timing',
          'Smoke Liga la tira el ÚLTIMO de los 3 de B',
        ],
      },
      {
        id: 'mirage-eco-t-1',
        name: 'Rush B (pistols)',
        type: 'eco',
        team: 'T',
        description: '5 por Apps',
        utilities: ['Smoke Market Window'],
        tips: [
          'Entrar pegados, moverse siempre, no pararse',
          'Objetivo: matar ancla B y robar rifle',
          'Si planta → postplant con lo que haya',
          'Prioridad: bajas y robos. Planta es bonus.',
        ],
      },
    ],
  },
  {
    id: 'nuke',
    name: 'Nuke',
    image: '/maps/nuke-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description:
      'Nuke es el mapa más CT-sided — los T deben JUGAR EN BLOQUE siempre. La clave es SEPARAR a los CT: si los CT juegan juntos, nunca entran. No morir en el default es lo MÁS IMPORTANTE en Nuke de terror.',
    sideFavor: 'CT-sided',
    callouts: {
      siteA: ['Caseta', 'Metal', 'Poti', 'Taxi', 'Galpón', 'Roja', 'Side A', 'Heaven', 'Rafters', 'Hut'],
      siteB: ['Rampa', 'Ducto', 'Secret', 'Wizard', 'Dobles', 'Vidrios', 'Breaking', 'Radio', 'Sin Salida'],
      middle: ['Roca', 'Fábrica', 'Montaña', 'Afuera', 'Pasaje', 'Vidrios', 'Galpón', 'Doble', 'Cascada'],
    },
    fundamentals: {
      t: [
        'Nuke es el mapa más CT-sided — los T deben JUGAR EN BLOQUE siempre',
        'La clave es SEPARAR a los CT: si los CT juegan juntos, nunca entran',
        '3 rutas principales: Afuera (Roca/Fábrica) · Hall/Rampa · Ducto/Secret',
        'Un lurker adentro es OBLIGATORIO cuando rodean afuera',
      ],
      ct: [
        'CT más fácil de Nuke — pero necesita COMUNICACIÓN y rotaciones limpias',
        'Setup base: 2 adentro (Caseta + Metal) · 1 Poti · 1 Taxi (rotador) · 1 Afuera (AP)',
        'El CT gana jugando compacto. Si el taxi baja y el AP mira, se sacan la info afuera en 20 seg',
      ],
    },
    strats: [
      {
        id: 'nuke-pistol-t-1',
        name: 'FaZe: Rodeo Montaña + Hall',
        type: 'pistol',
        team: 'T',
        description: '2 suben montaña → Taxi → Poti → Wizard · 3 van Hall → Rampa',
        setup: '2 Montaña + 3 Hall',
        utilities: ['Molotov taxi', 'HE taxi'],
        tips: [
          'Respawn 1: Rompe la puerta (mejor respawn)',
          'Respawn 2: Tira Moli taxi (para aislar CT de taxi)',
          'Los 2 de montaña: keblar OBLIGATORIO',
          'Timing es todo.',
        ],
      },
      {
        id: 'nuke-pistol-t-2',
        name: 'NaVi: 4 Afuera + Smoke Taxi',
        type: 'pistol',
        team: 'T',
        description: '4 afuera con flash · 1 solo Hold Hall · Smoke bugada arriba de Taxi',
        setup: '4 Afuera + 1 Hold',
        utilities: ['Smoke Taxi (bugada)', 'Flash'],
        tips: [
          'Smoke cae bugada arriba de taxi → el CT de taxi queda aislado y sin info',
          'Uno sube por montaña para rodear',
          'Glocks corren por todos los ángulos → imposible de counterar para 1-2 CTs',
          'En lobbies bajos es IMPARABLE.',
        ],
      },
      {
        id: 'nuke-buy-t-1',
        name: 'Rodeo Falcons: 4 Afuera + 1 Hold',
        type: 'buy',
        team: 'T',
        description: 'Smokes completas para dominar afuera',
        setup: '4 Afuera + 1 Hold Hall',
        utilities: ['Smoke corta', 'Smoke larga', 'Smoke pasaje', 'Molotov spawn'],
        tips: [
          '1 Hold en Hall: marca DE ATRÁS de la línea',
          '4 afuera: ganar espacio despacito, limpiar ángulos sin apurarse',
          'Finalización abajo: Smoke desde esquina breaking',
          'El de Hold jamás puede morir adelante.',
        ],
      },
      {
        id: 'nuke-buy-t-2',
        name: 'Explo Rampa NaVi: 4 Hall + 1 Afuera',
        type: 'buy',
        team: 'T',
        description: 'Setup inverso al Rodeo: 1 solo afuera (baja Secret) · 4 explotan por Rampa',
        setup: '4 Hall + 1 Secret',
        utilities: ['Smoke corta', 'Smoke larga', 'Smoke pasaje', 'Flash', 'Molotov'],
        tips: [
          '4 en Hall llegan a punto máximo → cuando el de afuera empieza a jugar → colapsan',
          'Ganar rampa con smoke: Flash → doble flash → moli Wizard',
          'El de Secret baja LENTO — ángulo por ángulo',
        ],
      },
    ],
  },
];

// Mapas adicionales del pool FACEIT (sin strats detalladas por ahora)
export const additionalMaps: MapDetail[] = [
  {
    id: 'inferno',
    name: 'Inferno',
    image: '/maps/inferno-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description: 'Mapa complejo con múltiples rutas. Requiere coordinación y control de información.',
    sideFavor: 'Balanced',
    callouts: {
      siteA: ['Bombsite A', 'Library', 'Apartments', 'Main'],
      siteB: ['Bombsite B', 'Banana', 'Graveyard'],
      middle: ['Underpass', 'Banana', 'Arch'],
    },
    fundamentals: {
      t: ['Coordinar entrada por aplicaciones', 'Controlar información'],
      ct: ['Defender posiciones defensivas', 'Mantener control de rotaciones'],
    },
    strats: [],
  },
  {
    id: 'vertigo',
    name: 'Vertigo',
    image: '/maps/vertigo-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description: 'Mapa vertical con alturas. El control de altura es crítico para ganar.',
    sideFavor: 'CT-sided',
    callouts: {
      siteA: ['Bombsite A', 'Rafters'],
      siteB: ['Bombsite B'],
      middle: ['Mid'],
    },
    fundamentals: {
      t: ['Usar altura a favor', 'Coordinar ataques'],
      ct: ['Defender desde posiciones altas', 'Rotar rápido'],
    },
    strats: [],
  },
  {
    id: 'ancient',
    name: 'Ancient',
    image: '/maps/ancient-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description: 'Mapa arqueológico con dos sites bien diferenciados y medio conectado.',
    sideFavor: 'Balanced',
    callouts: {
      siteA: ['Bombsite A', 'Main', 'Lobby'],
      siteB: ['Bombsite B', 'Water', 'Rafters'],
      middle: ['Mid', 'Plaza'],
    },
    fundamentals: {
      t: ['Ganar mid para abrir sites', 'Coordinar splits'],
      ct: ['Controlar mid', 'Rotas rápidas'],
    },
    strats: [],
  },
  {
    id: 'anubis',
    name: 'Anubis',
    image: '/maps/anubis-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description: 'Nuevo mapa con diseño complejo. Múltiples rutas y controlables.',
    sideFavor: 'Balanced',
    callouts: {
      siteA: ['Bombsite A', 'Main', 'Temple'],
      siteB: ['Bombsite B', 'Underpass'],
      middle: ['Mid', 'Plaza'],
    },
    fundamentals: {
      t: ['Explorar rutas alternativas', 'Obtener control de información'],
      ct: ['Defender múltiples entradas', 'Comunicación constante'],
    },
    strats: [],
  },
];

export const allMaps = [...mapsData, ...additionalMaps];
