import { allMaps as allMapsData } from '../maps';

export const allMaps = allMapsData;
    sideFavor: 'Balanced',
    callouts: {
      siteA: ['Largo', 'Fondo A', 'Fosa', 'Azul', 'Casa de fondo', 'Esquina', 'Rampa'],
      siteB: ['Túnel', 'Oscuro bajo', 'Oscuro alto', 'Side B', 'Auto', 'Carro', 'Altar', 'Rampa B'],
      middle: ['Xbox', 'Doble puerta', 'Corto', 'Ventana CT', 'Corredor', 'Barriles', 'Caja gorda'],
    },
    fundamentals: {
      t: [
        'No morir en el default es LO MÁS IMPORTANTE de terror en Dust 2.',
        'Setup 3-2: 3 hacia A (fondo/largo) + 2 hacia B (túnel/oscuro)',
        'Lurker fondo: juega lento, corta rotación, se suma al grupo según jugada',
        'Llegar shifteando a fondo sin que te vean = ronda ganada',
      ],
      ct: [
        'Siempre dominar FONDO o BARANDA. No perder las dos nunca.',
        'Ancla B nunca rota sin información clara — B es muy difícil de retakear',
        'Rotador con util siempre: Hi gorda es clave al venir medio',
        'El ancla B no puede morir en rush B — jamás.',
      ],
    },
    strats: [
      {
        id: 'd2-pistol-t-1',
        name: 'G2: Split Baranda + Fondo',
        category: 'Pistol',
        type: 'pistol',
        team: 'T',
        description: 'Split de pistol con presión A y fondo para forzar rotación temprana y robar armamento.',
        objectivePrincipal: 'Ganar control de baranda sin perder fondo para forzar al CT a rotar y abrir la puerta a una segunda fase.',
        difficulty: 'High',
        recommendedLevel: 'Competitivo avanzado',
        concept: 'Utilidad condicionada + ejecución dividida. El T busca crear un dilema entre defender baranda o fondo.',
        risks: ['Perder control de fondo rápido', 'Rotación CT temprana si falla la molotov', 'Entradas sin trade si alguien muere temprano'],
        whenToUse: 'Cuando se sospecha defensa dividida en A y el rival no ha cargado B temprano.',
        whenNotToUse: 'Contra un CT que juega baranda pasiva con doble ancla y muy conservador en fondo A.',
        failReaction: 'Si el primer jugador de baranda falla el contacto, repetir el split con más presión en fondo antes de obligar a un segundo engagement en A.',
        adaptationsPossible: 'Si B está abierto, convertir el split en una transición lenta hacia fondo con smoke puerta extra.',
        setup: '2 baranda · 3 fondo en punto máximo',
        playerDistribution: 'Dos jugadores presionan A, tres cubren fondo y ocupan espacios de rotación.',
        utilities: ['Smoke puerta', 'Molotov baranda', 'Flash x2'],
        timing: 'Tirar molotov baranda al segundo 20; mover fondo en el segundo 22; ejecutar contactos en el segundo 25.',
        importantSpaces: ['Baranda', 'Fondo A', 'Puerta', 'Xbox', 'Corto'],
        pointOfContact: 'Baranda primero; si se limpia, el segundo contacto entra por fondo para splitear A.',
        victoryCondition: 'Obtener un trade favorable en A y plantar con control de Puerta o Fondo.',
        postplant: 'Postplant en Puerta / Caja con dos cruces y un jugador cubriendo Corta o Long.',
        roles: {
          entry: {
            position: 'Baranda',
            objective: 'Ganar el ángulo rápido y obligar rotación.',
            utility: 'Flashear baranda y apoyar con molotov profundo si detecta presión.',
            timing: 'Entrada en el segundo 25, después de que la molotov esté activa.',
            responsibility: 'Abrir el espacio de A y forzar al CT a gastar util.',
            whatToLook: 'Contacto en baranda, cabeza de puente y posible jugador CT rotando de CT.',
            communication: '“Baranda limpia / contacto baranda”',
            onTeammateDeath: 'Fijarse si queda 1v1 en baranda y retrasar el segundo paso si no hay confirmado.',
            onNoContact: 'Rotar hacia fondo lentamente con el segundo entry y buscar trade desde Puerta.',
            postplantOrRetake: 'Mantener esquina de baranda postplant; usar el humo para reubicarse si el CT latea por Puerta.',
          },
          lurker: {
            position: 'Fondo A',
            objective: 'Cortar rotaciones y asegurar el rifle si el CT rota demasiado rápido.',
            utility: 'Flash corto y molotov para cubrir Puerta o Plataforma.',
            timing: 'Mantenerse retrasado hasta el segundo 24; reaccionar si hay información de rotación.',
            responsibility: 'No morir temprano y conservar armamento para el postplant.',
            whatToLook: 'Rotaciones a Estancia, Puerta y Xbox.',
            communication: '“Rotación Fondo / Puerta libre”',
            onTeammateDeath: 'Retroceder a Planta si el sitio está comprometido y evitar ser cortado en el bomb.',
            onNoContact: 'Avanzar a Plataforma para cortar Puerta y presionar al rotador.',
            postplantOrRetake: 'Tomar posición de caja larga o Puerta para cortes desde la entrada de Puerta.',
          },
          support: {
            position: 'Xbox',
            objective: 'Cubrir el entry y lanzar flashes sobre baranda/fondo.',
            utility: 'Dos flashes para baranda y un humo de puerta de emergencia.',
            timing: 'Flash en los segundos 23-24, apoyo durante el contacto principal.',
            responsibility: 'Garantizar el trade y liberar espacio para el entry.',
            whatToLook: 'Pies en baranda, movimiento en Puerta y potencial rotación de medio.',
            communication: '“Flash baranda, puerta casi”',
            onTeammateDeath: 'Recuperar el espacio de Xbox y retrasarse si el entry está comprometido.',
            onNoContact: 'Empujar con cuidado por Xbox hacia Puerta para verificar el rotador.',
            postplantOrRetake: 'Reubicarse a Short o Corta según planta y cubrir el balance desde Xbox.',
          },
          mid: {
            position: 'Xbox / Medio',
            objective: 'Mantener visión de rotaciones y evitar que CT llegue limpio a A.',
            utility: 'Flash para Puerta si aparece rotación de CT.',
            timing: 'Escuchar rotación al segundo 20; actuar si se ve movimiento de CT.',
            responsibility: 'No perder medio y avisar rotaciones tempranas.',
            whatToLook: 'Puerta, Conexion, Ventana.',
            communication: '“Uno rota CT / retardo”',
            onTeammateDeath: 'Cerrar la rotación hacia A y retrasar presión si es necesario.',
            onNoContact: 'Cortarse al área de Puerta para bloquear al rotador desde el centro.',
            postplantOrRetake: 'Apoyar postplant desde Xbox si se planta en A o cubrir una posible retake desde Puerta.',
          },
          anchor: {
            position: 'Fondo A',
            objective: 'Asegurar el control de fondo y servir de punto de trade.',
            utility: 'Molotov profundo para Plataforma o Puerta según información.',
            timing: 'Calcular avance hasta el segundo 24 y abrochar fuente de rotaciones.',
            responsibility: 'Ser la última línea que mantiene A bajo control.',
            whatToLook: 'Rotación por Puerta y movimiento del CT en Fondo.',
            communication: '“Fondo seguro / rotación hacia A”',
            onTeammateDeath: 'Cambiar a apoyo de período si el sitio se abre por Puerta.',
            onNoContact: 'Avanzar a Puerta con cautela y vigilar Corta.',
            postplantOrRetake: 'Ser el punto de corte desde Fondo o Puerta en la postplant.',
          },
          rotator: {
            position: 'Short',
            objective: 'Estar listo para caer a A si se abre el sitio o a B si emergen rotaciones.',
            utility: 'Smoke Puerta de emergencia / Flash corto.',
            timing: 'No rotar hasta que haya confirmación clara o el bomb esté en Planta.',
            responsibility: 'No sobrerotar; priorizar soporte al sitio principal.',
            whatToLook: 'Contacto en Baranda y posible humo de Puerta enemigo.',
            communication: '“No roto aún / falta confirmación”',
            onTeammateDeath: 'Mantener Short como ruta secundaria y alertar si CT cae al medio.',
            onNoContact: 'Presionar si el CT muestra información de debilidad en A.',
            postplantOrRetake: 'Apoyar desde Short para cortar a retakers que vienen por Puerta o Corta.',
          },
          awper: {
            position: 'Fondo A',
            objective: 'Controlar la rotación larga y castigar al CT que sale por Puerta.',
            utility: 'Ninguna adicional, enfocado en ángulos largos.',
            timing: 'Alinear a segundo 25 y esperar el primer movimiento de rotación.',
            responsibility: 'Ganarse el impacto largo o forzar al CT a cubrir Puerta.',
            whatToLook: 'Puerta, Plataforma, Corta.',
            communication: '“Voy largo / roti rota”',
            onTeammateDeath: 'Retroceder a cobertura profunda si el sitio entra al bomb.',
            onNoContact: 'Mantener ángulo largo y estar listo para cortar el push de retake.',
            postplantOrRetake: 'Usar ángulo profundo de Fondo para cortar Puerta y Corta en postplant.',
          },
          secondEntry: {
            position: 'Fondo A',
            objective: 'Servir de trade y limpiar el sitio una vez que baranda ha creado presión.',
            utility: 'Flash corto para Puerta si es necesario.',
            timing: 'Esperar al menos 1 segundo después del entry principal.',
            responsibility: 'Proteger al entry y cerrar el sitio con posicionamiento inteligente.',
            whatToLook: 'Puerta, Caja, Pasaje.',
            communication: '“Listo para entrar / trade listo”',
            onTeammateDeath: 'Cambiar a cierre de sitio desde Puerta y cubrir la planta.',
            onNoContact: 'Entrar con cuidado por Fondo y asegurar el trade con el entry.',
            postplantOrRetake: 'Mantener el ángulo de Puerta y rotar hacia Caja si el CT latea desde Largo.',
          },
        },
        tips: [
          'Uno compra smoke + moli. Moli a baranda (estructura) + smoke puerta',
          '2 jugadores ganan baranda cuando está activa la moli',
          'El primero de fondo hace straf (lleva la mira) → los otros 2 tradean',
        ],
      },
      {
        id: 'd2-pistol-t-2',
        name: 'Rush B (túnel)',
        category: 'Pistol',
        type: 'pistol',
        team: 'T',
        description: 'Rush de túnel con utility mínima para neutralizar el primer ancla de B y plantar rápido.',
        objectivePrincipal: 'Evitar que el CT organice la defensa de B y robar armamento antes del segundo 20.',
        difficulty: 'Medium',
        recommendedLevel: 'Competitivo',
        concept: 'Velocidad y presión. Esto no es un split; es un compromiso total con B.',
        risks: ['Fallo en smoke de puerta', 'flasheos mal sincronizados', 'mala entrada de la mancha'],
        whenToUse: 'Contra anti-eco CT o cuando se espera que defienda B con pistolas.',
        whenNotToUse: 'Cuando el CT tiene rifles en B y puede castigar la entrada con smoke de escalera.',
        failReaction: 'Si se recibe fuego desde la primera esquina, plantar y jugar site con posiciones cruzadas desde boca túnel y oscuro alto.',
        adaptationsPossible: 'Si no se logra smoke puerta, variar a un push por Oscuro Alto con un segundo flash.',
        setup: '5 por túnel',
        playerDistribution: 'Todos los jugadores entran juntos, manteniendo línea de trade cercana.',
        utilities: ['Flash x2 entry', 'Smoke puerta'],
        timing: 'Smoke puerta justo antes de la entrada y flashes inmediatos al llegar a boca.',
        importantSpaces: ['Ojo de túnel', 'Puerta', 'Oscuro alto', 'Oscuro bajo'],
        pointOfContact: 'Entrada por túnel; el primer daño debe salir desde la mancha y la puerta.',
        victoryCondition: 'Derribar al ancla y plantar con control de Puerta y Oscuro alto.',
        postplant: 'Postplant en Puerta / Oscuro con un jugador cubriendo toque y otro la retralata del CT desde B.',
        roles: {
          entry: {
            position: 'Boca túnel',
            objective: 'Forzar el contacto inicial y exponer al ancla.',
            utility: 'Primer flash hacia puerta / oscuro alto.',
            timing: 'Entrar en el instante después de que la smoke comienza a caer.',
            responsibility: 'Ser la chispa del rush, absorber el primer fuego del defensor.',
            whatToLook: 'Ojo de túnel, puerta, oscuro alto.',
            communication: '“Vamos por túnel, voy primero”',
            onTeammateDeath: 'No frenar el rush; avanzar con el siguiente entry y buscar trade inmediato.',
            onNoContact: 'Plantarse rápido y consolidar sitio con el segundo entry cubriendo la puerta.',
            postplantOrRetake: 'Plantarse en la boca del túnel y usar sombra de humo para cortar retake.',
          },
          lurker: {
            position: 'Oscuro alto',
            objective: 'Cerrar la rotación corta y evitar que el CT vuelva a B desde jardín.',
            utility: 'Flash de apoyo si hay contacto en puerta.',
            timing: 'Llegar a Oscuro alto tras el primer contacto de túnel.',
            responsibility: 'Proteger la retaguardia y generar presión en oscuro alto.',
            whatToLook: 'Rotación por jardín y ruta de retake por oscuro bajo.',
            communication: '“Oscuro alto listo / giro blanco”',
            onTeammateDeath: 'Bajar a oscuro bajo para proteger el sitio plantado.',
            onNoContact: 'Forzar oscuro alto y ayudar al site con información de CT moviéndose.',
            postplantOrRetake: 'Mantener oscuro alto para cortar retake y asegurar el plant.',
          },
          support: {
            position: 'Detrás del entry',
            objective: 'Asegurar el trade y lanzar flashes de seguimiento.',
            utility: 'Segundo flash y smoke de puerta si es necesario.',
            timing: 'Coordinar con el entry al segundo 18-20.',
            responsibility: 'Ser fiable en el segundo contacto y cerrar líneas de trade.',
            whatToLook: 'Receiver del entry, puerta, y oscuro alto.',
            communication: '“Traider listo / flash puerta”',
            onTeammateDeath: 'Empujar sobre el cuerpo del entry y asegurar el sitio.',
            onNoContact: 'Avanzar por detrás del entry para confirmar el sitio limpio.',
            postplantOrRetake: 'Formar parte de la cruz en Puerta y cubrir primer corte de retake.',
          },
          mid: {
            position: 'Medio no aplica',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'Esta ronda es un commit total a B, el medio no se usa.',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          anchor: {
            position: 'Final del túnel',
            objective: 'Asegurar la puerta de entrada y el plant.',
            utility: 'Smoke puerta adicional si el sitio no está completamente limpio.',
            timing: 'No avanzar hasta que haya suficiente compañía detrás.',
            responsibility: 'Ser la última línea de mantenimiento del sitio.',
            whatToLook: 'Puerta, oscuro alto y rotaciones por jardín.',
            communication: '“Puerta segura / plantando”',
            onTeammateDeath: 'Tomar la posición del entry si este muere temprano.',
            onNoContact: 'Asegurarse de que el sitio esté claro antes de plantar.',
            postplantOrRetake: 'Cubrir el plant desde la boca del túnel y apoyarse con humo.',
          },
          rotator: {
            position: 'No rotador directo',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'Todos los jugadores están comprometidos en B.',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          awper: {
            position: 'No aplicable',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'N/A',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          secondEntry: {
            position: 'Segundo en túnel',
            objective: 'Pegar el trade y cerrar la rotación de B.',
            utility: 'Flash de apoyo si el entry se queda viendo.',
            timing: 'Entrar inmediatamente tras el primer impacto del entry.',
            responsibility: 'Convertir la apertura del entry en control de sitio.',
            whatToLook: 'Puerta, oscuro alto, retador de CT.',
            communication: '“Segunda entrada lista”',
            onTeammateDeath: 'Empujar el sitio y asegurar la planta.',
            onNoContact: 'Cubrir al entry y confirmar el plant.',
            postplantOrRetake: 'Formar la cruz en puerta y contener rotaciones lentas.',
          },
        },
        tips: [
          'Respawn 3 (CLAVE): smoke puerta corriendo + dos flashes desde la mancha',
          'Objetivo: smoke puerta activa + CT flasheado = entrar limpio y matar ancla',
          'Si el respawn 3 no tira bien las latas, el rush pierde. Práctica obligatoria.',
        ],
      },
      {
        id: 'd2-pistol-ct-1',
        name: 'Mongols: 1-1-1-2B (Duals)',
        type: 'pistol',
        team: 'CT',
        description: '1 fondo · 1 baranda (FB+HE) · 1 oscuro bajo (Duals) · 2 en B',
        setup: '1-1-1-2 distribuido',
        utilities: ['Duals', 'FB', 'HE'],
        tips: [
          'Jugador Duals: se mete oscuro bajo pegado a caja — letal a corta distancia',
          '2 de B: anti + se pegan a boca oscuro al timing — pullean con el de oscuro',
          'Dropear buenas duals a jugador habilidoso. El ancla oscuro tiene que brillar.',
        ],
      },
      {
        id: 'd2-buy-t-1',
        name: 'Exec Baranda (Pain Style)',
        category: 'Full Buy',
        type: 'buy',
        team: 'T',
        description: 'Ejecución estructurada por A con doble smoke de baranda y combo de utility en caja y puerta.',
        objectivePrincipal: 'Controlar A con util y aislar al CT de fondo para plantar en Puerta sin riesgo de rotación temprana.',
        difficulty: 'Very High',
        recommendedLevel: 'Tier competitivo',
        concept: 'Aislar el sitio con capas de utility y obligar a la defensa a jugar bajo presión dividida.',
        risks: ['Fallo en la segunda smoke de baranda', 'Perder el trade en caja', 'Plantar sin control de Puerta'],
        whenToUse: 'Ronda de victoria o cuando el rival juega agresivo en B y deja A más abierta.',
        whenNotToUse: 'Contra un CT que ya demostró rotaciones rápidas y control de fondo A.',
        failReaction: 'Si el primer contacto falla, transicionar a un split lento por Long con un segundo molotov a Puerta.',
        adaptationsPossible: 'Si el CT rota lento, usar la smoke de baranda para forzar a que el defensor juegue con una sola high ground.',
        setup: '4-5 comprando completo',
        playerDistribution: '2 en baranda, 1 en caja media, 1 en fondo corto y 1 en Puerta.',
        utilities: ['Doble smoke baranda', 'Molotov caja', 'Flash x2'],
        timing: 'Smokes en el segundo 22; entrada total en el 24; planta antes del 30.',
        importantSpaces: ['Baranda', 'Caja', 'Puerta', 'Long A', 'Fondo A'],
        pointOfContact: 'Baranda y Caja al mismo tiempo; La Puerta se asegura con delayed push.',
        victoryCondition: 'Plantar en Puerta con control de caja y baranda, manteniendo dos cruces claras.',
        postplant: 'Postplant de Puerta/Long con smoke de Puerta si se planta en largo y un cruzado en caja.',
        roles: {
          entry: {
            position: 'Baranda',
            objective: 'Abrir el espacio y sacar al defensor de Puerta.',
            utility: 'Flash hacia caja y smoke de baranda primero.',
            timing: 'Entrada a segundo 24 con support pegado.',
            responsibility: 'Ser la presión de primer contacto en A; no forzar ángulos múltiples.',
            whatToLook: 'Caja, Puerta, rotaciones de corto.',
            communication: '“Baranda presionada / caja alive”',
            onTeammateDeath: 'Mantener la línea de trade sin avanzar demasiado.',
            onNoContact: 'Cambiar a retraso y dar espacio al segundo entry.',
            postplantOrRetake: 'Cubrir la Puerta y mover a Long según el plant.',
          },
          lurker: {
            position: 'Fondo corto',
            objective: 'Tomar el rifle si el CT sale de caja y cortar rotaciones por Largo.',
            utility: 'Molotov a Puerta si hay presencia.',
            timing: 'Avance tras la primera smoke y comienza a limpiar ángulos.',
            responsibility: 'Ser el recorte de los rotadores y el guardián del sitio plantado.',
            whatToLook: 'Largo, Puerta, Caja.',
            communication: '“Fondo corto limpio / rotación posible”',
            onTeammateDeath: 'Tomar el foco de sitio si el entry de baranda cae.',
            onNoContact: 'Avanzar con cautela y esperar a que el segundo entry empuje Caja.',
            postplantOrRetake: 'Ser el punto de corte hacia Largo o Puerta durante la postplant.',
          },
          support: {
            position: 'Caja',
            objective: 'Asegurar el trade y limpiar información en Caja.',
            utility: 'Flash largo y molotov de caja.',
            timing: 'Flash en sincronía con el entry de baranda.',
            responsibility: 'Quedar en el sitio y ser el segundo punto de trade.',
            whatToLook: 'Caja, Puerta, baranda.',
            communication: '“Caja limpia / no baranda”',
            onTeammateDeath: 'Cuidar la Puerta y retroceder ligeramente a Caja.',
            onNoContact: 'Rotar hacia Puerta y bloquear cualquier intento de defensa.',
            postplantOrRetake: 'Mantener el ángulo en Caja y preparar un corte a Puerta.',
          },
          mid: {
            position: 'Medio no aplica',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'N/A',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          anchor: {
            position: 'Puerta',
            objective: 'Asegurar el plant y ser la última referencia de sitio.',
            utility: 'Smoke de Puerta o flash de apoyo.',
            timing: 'No avanzar antes del contacto de baranda.',
            responsibility: 'No permitir que el CT recupere Puerta.',
            whatToLook: 'Caja, baranda, oscuro.',
            communication: '“Puerta lista / plantando”',
            onTeammateDeath: 'Cerrar baranda desde Puerta y retrasar el plant si hace falta.',
            onNoContact: 'Volverse el punto de corte principal en Puerta.',
            postplantOrRetake: 'Cubrir el lado derecho de Puerta y reubicarse a Largo si es necesario.',
          },
          rotator: {
            position: 'No rotador directo',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'N/A',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          awper: {
            position: 'No aplicable',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'N/A',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          secondEntry: {
            position: 'Caja / Puerta',
            objective: 'Ser el trade confiable y asegurar el sitio después del primer contacto.',
            utility: 'Flash de apoyo y posible humo de Puerta.',
            timing: 'Seguir al entry principal con medio segundo de retraso.',
            responsibility: 'Proteger al entry y fijar el sitio para plantar.',
            whatToLook: 'Caja, Puerta, baranda.',
            communication: '“Segundo listo / trade confirmado”',
            onTeammateDeath: 'Entrar para asegurar el sitio y evitar un reset.',
            onNoContact: 'Avanzar con cuidado y limpiar la rotación interna desde Caja.',
            postplantOrRetake: 'Ayudar al entry a cerrar Puerta y cubrir el corte hacia Largo.',
          },
        },
        tips: [
          'Smoke 1 (David): agachado escalera, apunta ventana abajo izquierda',
          'Smoke 2 (NK caja): agachado, puntito blanco, se choca con caja',
          'Entry fragers entran mirando UN ángulo solo',
          'Lo que NO puede faltar: doble smoke + combo NK. Todo lo demás es bonus.',
        ],
      },
      {
        id: 'd2-buy-t-2',
        name: 'Split Medio-B (Spirit)',
        type: 'buy',
        team: 'T',
        description: '2-3 por medio → B · 2 por oscuro bajo (juro) coordinados',
        setup: 'Split con entrada por Medio',
        utilities: ['Smoke CT caja gorda', 'Molotov x2', 'Flash'],
        tips: [
          'La smoke de caja gorda es la más importante — sin ella el CT los mata a todos',
          'Los de oscuro: moli caja gorda + moli fondo altar',
          'Los de oscuro calan info → si no hay nadie → se mandan limpiando ángulos',
        ],
      },
      {
        id: 'd2-buy-t-3',
        name: 'Rush A largo (Vitality)',
        type: 'buy',
        team: 'T',
        description: 'Solo 1 jugador tira toda la util. 5 rushean largo.',
        setup: '1 tira util · 5 rushean',
        utilities: ['Smoke esquina largo', 'Flash x2', 'Molotov'],
        tips: [
          'Un solo jugador tira TODO. Los demás solo corren y matan.',
          'Flash ancha temprana (para el que tira util antiflash)',
          'Moli detrás del humo (para reagresión CT)',
          'Muy eficiente en pug.',
        ],
      },
      {
        id: 'd2-eco-t-1',
        name: 'Rush B (5 túnel)',
        type: 'eco',
        team: 'T',
        description: '5 por túnel sin demorarse',
        utilities: ['Smoke puerta', 'Flash x2'],
        tips: [
          'Respawn 3 smokea puerta corriendo (CLAVE)',
          'Respawn 1+2 flashean al CT de entrada',
          'Objetivo: matar ancla + robar rifle',
          'Sin smoke puerta el rush no sale.',
        ],
      },
      {
        id: 'd2-eco-t-2',
        name: 'Default pasivo',
        type: 'eco',
        team: 'T',
        description: 'Uno en cada zona → buscar picks',
        utilities: [],
        tips: [
          'No atacar sin util — esperar errores',
          'Si roban rifle → atacar esa zona',
          'Lurker fondo: presionar, no morir',
          'Usar tiempo. CT impaciente = pick gratis.',
        ],
      },
      {
        id: 'd2-force-t-1',
        name: 'SMG rush B',
        type: 'force',
        team: 'T',
        description: 'Rush B con Mac-10 / SMG',
        setup: '5 rushean con SMG',
        utilities: ['Smoke puerta', 'Flash x2'],
        tips: [
          'Al menos smoke puerta corriendo',
          'Flash x2 entry — sorprender al CT',
          'Plantar y jugar postplant',
          'Ventaja: CT guarda para próxima ronda.',
        ],
      },
      {
        id: 'd2-force-t-2',
        name: 'Split largo+corto',
        type: 'force',
        team: 'T',
        description: '3 largo + 2 corto/medio → split A',
        setup: 'Split A',
        utilities: ['1 smoke esquina largo'],
        tips: [
          'Sin exec completo: explotar rapido',
          'Si tienen 1 smoke → esquina largo',
          'Timing: ambos grupos colapsan juntos',
          'Prioridad: matar AP y robar arma.',
        ],
      },
    ],
  },
  {
    id: 'mirage',
    name: 'Mirage',
    image: '/maps/mirage-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description:
      'Quien controla medio controla el mapa. Mid → Connector abre A; Short abre B. Los T necesitan obtener control de medio para decidir el flujo de la ronda.',
    sideFavor: 'CT-sided',
    callouts: {
      siteA: ['Ramp', 'Palacio', 'Tetris', 'Sándwich', 'CT', 'Jungla', 'Banco', 'Cabeciña'],
      siteB: ['Apps', 'Van', 'Bench', 'Pillar', 'Default B', 'Market', 'Short'],
      middle: ['Top Mid', 'Window', 'Connector (short)', 'Underpass (L)', 'Moscú', 'Liga'],
    },
    fundamentals: {
      t: [
        'Controlar medio es CLAVE: Mid → Connector abre A; Short abre B',
        'Split A: 3 Liga · 1 Caverna (lateo) · 1 Palacio (cover)',
        'Los 3 de liga NO van juntos — 1 lleva arma, 2 saltan. Moverse = difícil de matar',
      ],
      ct: [
        'Setup base 2-1-2: A anchor (Ticket/CT) + Mid (Window+DL) + B anchor (Van/Bench)',
        'Buda, DL y Liga: comunicación constante. Ellos marcan el rumbo de la ronda',
        'Moli Carroza temprano para negar salida medio',
      ],
    },
    strats: [
      {
        id: 'mirage-pistol-t-1',
        name: 'Liquid Split A',
        category: 'Pistol',
        type: 'pistol',
        team: 'T',
        description: 'Split rápido por A con liga, palacio y caverna para forzar a los CT a decidir entre short y palacio.',
        objectivePrincipal: 'Aislar el site A con presión en Liga y palacio, obligando a los CT a revelar su setup.',
        difficulty: 'High',
        recommendedLevel: 'Competitivo',
        concept: 'Utilidad agresiva y movimiento constante para hacer sentir incómodos a los CT desde el inicio.',
        risks: ['Perder el first duelist en liga', 'comunicaciones tardías de caverna', 'planta difícil sin control de CT'],
        whenToUse: 'Contra un CT que defiende A con una línea larga pasiva en palacio y poca presencia en medio.',
        whenNotToUse: 'Cuando el CT ya ha mostrado stacks en palacio o un A-passive con dos rifles largos.',
        failReaction: 'Si el primer contacto en Liga se pierde, entrar en grupo y actuar como un pseudo-exec sobre palacio y puerta.',
        adaptationsPossible: 'Si palacio está empacado, convertir el split en A corto con caverna y smoke de puerta extra.',
        setup: '3-1-1 Liga/Caverna/Palacio',
        playerDistribution: 'Tres en liga, uno en caverna y uno cubre palacio para un posible late push.',
        utilities: ['Smoke Triple (bugada)', 'Smoke Jungla'],
        timing: 'Liga empieza al 20; caverna latea hasta ver el contacto o no; palacio queda en ready.',
        importantSpaces: ['Top Mid', 'Short', 'Palacio', 'Jungla', 'Puerta'],
        pointOfContact: 'Liga primero; si no hay resistencia allí, el resto del equipo presiona palacio/caverna.',
        victoryCondition: 'Ganar A con espacio limpio en Puerta y Jungle para poder plantar y jugar el postplant.',
        postplant: 'Postplant en Puerta/Jungle con dos cruces y un jugador de apoyo en Palacio.',
        roles: {
          entry: {
            position: 'Liga',
            objective: 'Forzar el primer duelo y abrir lugar para el equipo.',
            utility: 'Smoke triple bugada y flash de salida.',
            timing: 'Inicia el movimiento al segundo 20.',
            responsibility: 'Ser la chispa del split; no buscar peeks innecesarios.',
            whatToLook: 'Top Mid, Short, contacto en Jungle.',
            communication: '“Liga entrando / no llave”',
            onTeammateDeath: 'Empujar con el segundo entry y cubrir la rotación de CT hacia Short.',
            onNoContact: 'Avanzar hacia Jungle y apoyar con util a Paledia.',
            postplantOrRetake: 'Reubicar a Jungle o Puerta para cortar el retake B.',
          },
          lurker: {
            position: 'Palacio',
            objective: 'Mantener la posibilidad de entrar luego como late o cerrar rotaciones por CT.',
            utility: 'Smoke Jungla y flash de apoyo.',
            timing: 'Se queda retrasado hasta que Liga muestra si hay espacio o no.',
            responsibility: 'No morir temprano y ser la amenaza de palacio.',
            whatToLook: 'Rotaciones de Medio, Jungla y CT.',
            communication: '“Palacio listo / no hay medio”',
            onTeammateDeath: 'Correr al sitio por Puerta si la entrada por Liga está comprometida.',
            onNoContact: 'Entrar por Palacio con fuerza y tomar la esquina de Jungle.',
            postplantOrRetake: 'Cubrir el key de Jungle y evitar que el CT se rote fácil por CT.',
          },
          support: {
            position: 'Caverna',
            objective: 'Someter a Para y dar información de B o CT.',
            utility: 'Flash de salida y posibles molotovs de palacio.',
            timing: 'Latea hasta confirmar el inicio del contacto en Liga.',
            responsibility: 'Ser el segundo apoyo y fall back si se exige rotación.',
            whatToLook: 'Banana, CT, posible push por Short.',
            communication: '“Caverna lista / no hay B”',
            onTeammateDeath: 'Cortar posibles rotaciones desde Medio hacia A.',
            onNoContact: 'Entrar a Jungle para ayudar al postplant.',
            postplantOrRetake: 'Tomar el ángulo de Jungle y dar cobertura a Puerta.',
          },
          mid: {
            position: 'No aplica',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'N/A',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          anchor: {
            position: 'Puerta',
            objective: 'Proteger la rotación corta y el sitio plantado.',
            utility: 'Smoke adicional si el CT reingresa por CT.',
            timing: 'No entra hasta que Liga y Palacio han creado presión.',
            responsibility: 'Ser el guardián del paso de Puerta y Jungle.',
            whatToLook: 'Puerta, Jungle, CT.',
            communication: '“Puerta segura / jungle lista”',
            onTeammateDeath: 'Retirarse a Jungle si el sitio se complica.',
            onNoContact: 'Ser la ayuda principal para el postplant en Puerta.',
            postplantOrRetake: 'Mantener la cruz de Puerta y Jungle para cortar retake.',
          },
          rotator: {
            position: 'No aplica',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'N/A',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          awper: {
            position: 'No aplica',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'N/A',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          secondEntry: {
            position: 'Liga segunda línea',
            objective: 'Dar trade al primer entry y cerrar el sitio.',
            utility: 'Flash de continuación para Jungle o Puerta.',
            timing: 'Seguir al primer entry tras el contacto inicial.',
            responsibility: 'Ser la seguridad y la segunda ola de tuerzas.',
            whatToLook: 'Baraja de fuego de CT, Jungle, Puerta.',
            communication: '“Segundo listo / trade en camino”',
            onTeammateDeath: 'Tomar el control del sitio y asegurar la limpieza de Jungle.',
            onNoContact: 'Avanzar para cerrar el gap y apoyar el postplant.',
            postplantOrRetake: 'Apoyar la cruz de Puerta y Jungle para cortar retake.',
          },
        },
        tips: [
          '3 corren Liga con Glock — saltando, moviéndose siempre',
          'Caverna tira smokes, latea en liga',
          'Si matan 1-2 → intentar comer site. Si no → mantener posición',
        ],
      },
      {
        id: 'mirage-pistol-t-2',
        name: 'Rush B',
        type: 'pistol',
        team: 'T',
        description: '5 por Apps · Smokes Market Window + Market Door',
        setup: '5 Apps',
        utilities: ['Smoke Market Window', 'Smoke Market Door'],
        tips: [
          'Un jugador tira ambas smokes desde corner TV room',
          'Todos van Apps sin demorarse nada',
          'Entran pegados por Van y Bench',
          'Funciona anti-eco CT o cuando sospechan stack A. El momentum lo es todo.',
        ],
      },
      {
        id: 'mirage-buy-t-1',
        name: 'Full Exec A (FaZe)',
        category: 'Full Buy',
        type: 'buy',
        team: 'T',
        description: 'Ejecutar A con caverna y palacio apoyados por cuatro smokes que bloquean CT y liberan Jungle.',
        objectivePrincipal: 'Tomar A con util completa, aislar al defensor de CT y plantar con control de Jungle y Puerta.',
        difficulty: 'Very High',
        recommendedLevel: 'Tier competitivo',
        concept: 'Doblar la presión desde múltiples ángulos para forzar al CT a defender con constantes cambios de posición.',
        risks: ['Fallo de smoke de Jungle', 'CT corta el apoyo desde Paseo', 'pérdida de trade en Palácio'],
        whenToUse: 'Cuando el rival juega más pesado en B o mid y A está menos defendido.',
        whenNotToUse: 'Si el CT es fuerte en B y tiene el sleeper o el ancla inteligente en CT.',
        failReaction: 'Si el primer contacto falla, meter utility de retardo y tomar Puerta con más cautela.',
        adaptationsPossible: 'Si los CT presionan demasiado Jungle, rotar parte del equipo a Puerta y tirar una segunda smoke de CT.',
        setup: '4-1 Caverna/Palacio',
        playerDistribution: 'Dos en Caverna, uno en Palacio, uno en Jungle y uno en Puerta.',
        utilities: ['Smoke Cabeciña', 'Smoke Banco', 'Smoke CT', 'Molotov x2'],
        timing: 'Smoke Jungle al 18, smokes de CT y Banco al 20, palacio avanza al 22.',
        importantSpaces: ['Jungla', 'Puerta', 'CT', 'Palacio', 'Banco'],
        pointOfContact: 'Caverna y Palácio a la vez; Jungle sirve de apoyo para cerrar el sitio.',
        victoryCondition: 'Plantar en Puerta/Long con dos cruces claras y control de Jungle.',
        postplant: 'Postplant de Puerta con un jugador en Jungle y otro en Banco para cortar rotaciones.',
        roles: {
          entry: {
            position: 'Caverna',
            objective: 'Entrar rápido y eliminar al primer defensor de A.',
            utility: 'Flash de entrada y smoke de Jungle si hay presencia.',
            timing: 'Iniciar el push a segundo 22.',
            responsibility: 'Ser la primera fuerza de ataque en A y atraer atención.',
            whatToLook: 'Puerta, Jungle, CT.',
            communication: '“Caverna a punto / jungle pronto”',
            onTeammateDeath: 'Retirarse a Jungle o Puerta según la presión enemiga.',
            onNoContact: 'Seguir con el segundo entry y limpiar Puerta lentamente.',
            postplantOrRetake: 'Cubrir el plant desde Jungle y Puerta.',
          },
          lurker: {
            position: 'Palacio',
            objective: 'Presionar al defensor de CT y ocupar el lado opuesto del sitio.',
            utility: 'Molotov a CT o flash de salida.',
            timing: 'Mantenerse en palacio hasta el ingreso de Caverna.',
            responsibility: 'Ser la amenaza que evita que el CT rote libremente a Jungle.',
            whatToLook: 'Rotaciones de medio y movimiento en CT.',
            communication: '“Palacio listo / CT nitro”',
            onTeammateDeath: 'Salirse si el sitio se pierde y evitar ser aislado en palacio.',
            onNoContact: 'Bajar a Jungle o Puerta para apoyar la postplant.',
            postplantOrRetake: 'Cortar desde Palacio si el CT intenta recuperar el sitio.',
          },
          support: {
            position: 'Jungla',
            objective: 'Proteger el plant y ser la referencia de corte de retake.',
            utility: 'Smoke CT y molotov de Banco.',
            timing: 'Colocar la smoke antes de que Caverna entre en el sitio.',
            responsibility: 'Ser el punto de apoyo en la postplant y evitar contras.',
            whatToLook: 'Puerta, CT, Banco.',
            communication: '“Jungla al fuego / puerta limpia”',
            onTeammateDeath: 'Sostener Jungle y cubrir a Puerta con el humo.',
            onNoContact: 'Bajar a Puerta con más presión para confirmar el sitio.',
            postplantOrRetake: 'Ser el punto de corte por Jungla o CT.',
          },
          mid: {
            position: 'No aplica',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'N/A',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          anchor: {
            position: 'Puerta',
            objective: 'Asegurar la planta y blindar el lado corto del site.',
            utility: 'Flash o smoke de Puerta si el CT aparece.',
            timing: 'Avanzar solo cuando el sitio esté mayormente bajo control.',
            responsibility: 'Ser la última línea de defensa del plant.',
            whatToLook: 'Caja, CT, Jungla.',
            communication: '“Planta en marcha / Puerta bajo control”',
            onTeammateDeath: 'Cerrar Puerta y evitar la reentrada enemiga.',
            onNoContact: 'Reubicar a largo para la postplant si el CT no aparece.',
            postplantOrRetake: 'Mantener el plant desde Puerta y ayudar a Jungle a cortar el retake.',
          },
          rotator: {
            position: 'No aplica',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'N/A',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          awper: {
            position: 'No aplicable',
            objective: 'N/A',
            utility: 'N/A',
            timing: 'N/A',
            responsibility: 'N/A',
            whatToLook: 'N/A',
            communication: 'N/A',
            onTeammateDeath: 'N/A',
            onNoContact: 'N/A',
            postplantOrRetake: 'N/A',
          },
          secondEntry: {
            position: 'Puerta / Caja',
            objective: 'Ser el trade del entry y cerrar el sitio con util.',
            utility: 'Flash de continuación y smoke de Puerta si es necesario.',
            timing: 'Seguir a la entrada principal en el segundo 23-24.',
            responsibility: 'Asegurar el sitio y confirmar el plant.',
            whatToLook: 'Puerta, Caja, CT.',
            communication: '“Segundo en camino / trade activo”',
            onTeammateDeath: 'Tomar el sitio si el entry principal cae.',
            onNoContact: 'Entrar y asegurar Puerta con el apoyo de Jungle.',
            postplantOrRetake: 'Apoyar la formación de la cruz en Puerta y Jungle.',
          },
        },
        tips: [
          'Rein: smoke Cabeciña (doble click Jantrow) + Banco',
          'Brocky: smoke CT + flash LARGA que fea CT',
          'Entry fragers van PEGADOS a smokes — no salen de una',
          'Carrigan NO se expone para el humo hasta que esté todo clear',
        ],
      },
      {
        id: 'mirage-buy-t-2',
        name: 'Split LB (NaVi)',
        type: 'buy',
        team: 'T',
        description: '2 por Medio → L · 3 por B → colapso simultáneo',
        setup: '2 Mid + 3 B',
        utilities: ['Smoke Buda (respawn)', 'Smoke Liga (rápida)', 'Smoke Pasaje (opcional)'],
        tips: [
          '2 de medio dominan Mid → matan → se mandan para L',
          '3 de B llegan a punto máximo (Van) y esperan el timing',
          'Smoke Liga la tira el ÚLTIMO de los 3 de B',
        ],
      },
      {
        id: 'mirage-eco-t-1',
        name: 'Rush B (pistols)',
        type: 'eco',
        team: 'T',
        description: '5 por Apps',
        utilities: ['Smoke Market Window'],
        tips: [
          'Entrar pegados, moverse siempre, no pararse',
          'Objetivo: matar ancla B y robar rifle',
          'Si planta → postplant con lo que haya',
          'Prioridad: bajas y robos. Planta es bonus.',
        ],
      },
    ],
  },
  {
    id: 'nuke',
    name: 'Nuke',
    image: '/maps/nuke-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description:
      'Nuke es el mapa más CT-sided — los T deben JUGAR EN BLOQUE siempre. La clave es SEPARAR a los CT: si los CT juegan juntos, nunca entran. No morir en el default es lo MÁS IMPORTANTE en Nuke de terror.',
    sideFavor: 'CT-sided',
    callouts: {
      siteA: ['Caseta', 'Metal', 'Poti', 'Taxi', 'Galpón', 'Roja', 'Side A', 'Heaven', 'Rafters', 'Hut'],
      siteB: ['Rampa', 'Ducto', 'Secret', 'Wizard', 'Dobles', 'Vidrios', 'Breaking', 'Radio', 'Sin Salida'],
      middle: ['Roca', 'Fábrica', 'Montaña', 'Afuera', 'Pasaje', 'Vidrios', 'Galpón', 'Doble', 'Cascada'],
    },
    fundamentals: {
      t: [
        'Nuke es el mapa más CT-sided — los T deben JUGAR EN BLOQUE siempre',
        'La clave es SEPARAR a los CT: si los CT juegan juntos, nunca entran',
        '3 rutas principales: Afuera (Roca/Fábrica) · Hall/Rampa · Ducto/Secret',
        'Un lurker adentro es OBLIGATORIO cuando rodean afuera',
      ],
      ct: [
        'CT más fácil de Nuke — pero necesita COMUNICACIÓN y rotaciones limpias',
        'Setup base: 2 adentro (Caseta + Metal) · 1 Poti · 1 Taxi (rotador) · 1 Afuera (AP)',
        'El CT gana jugando compacto. Si el taxi baja y el AP mira, se sacan la info afuera en 20 seg',
      ],
    },
    strats: [
      {
        id: 'nuke-pistol-t-1',
        name: 'FaZe: Rodeo Montaña + Hall',
        type: 'pistol',
        team: 'T',
        description: '2 suben montaña → Taxi → Poti → Wizard · 3 van Hall → Rampa',
        setup: '2 Montaña + 3 Hall',
        utilities: ['Molotov taxi', 'HE taxi'],
        tips: [
          'Respawn 1: Rompe la puerta (mejor respawn)',
          'Respawn 2: Tira Moli taxi (para aislar CT de taxi)',
          'Los 2 de montaña: keblar OBLIGATORIO',
          'Timing es todo.',
        ],
      },
      {
        id: 'nuke-pistol-t-2',
        name: 'NaVi: 4 Afuera + Smoke Taxi',
        type: 'pistol',
        team: 'T',
        description: '4 afuera con flash · 1 solo Hold Hall · Smoke bugada arriba de Taxi',
        setup: '4 Afuera + 1 Hold',
        utilities: ['Smoke Taxi (bugada)', 'Flash'],
        tips: [
          'Smoke cae bugada arriba de taxi → el CT de taxi queda aislado y sin info',
          'Uno sube por montaña para rodear',
          'Glocks corren por todos los ángulos → imposible de counterar para 1-2 CTs',
          'En lobbies bajos es IMPARABLE.',
        ],
      },
      {
        id: 'nuke-buy-t-1',
        name: 'Rodeo Falcons: 4 Afuera + 1 Hold',
        type: 'buy',
        team: 'T',
        description: 'Smokes completas para dominar afuera',
        setup: '4 Afuera + 1 Hold Hall',
        utilities: ['Smoke corta', 'Smoke larga', 'Smoke pasaje', 'Molotov spawn'],
        tips: [
          '1 Hold en Hall: marca DE ATRÁS de la línea',
          '4 afuera: ganar espacio despacito, limpiar ángulos sin apurarse',
          'Finalización abajo: Smoke desde esquina breaking',
          'El de Hold jamás puede morir adelante.',
        ],
      },
      {
        id: 'nuke-buy-t-2',
        name: 'Explo Rampa NaVi: 4 Hall + 1 Afuera',
        type: 'buy',
        team: 'T',
        description: 'Setup inverso al Rodeo: 1 solo afuera (baja Secret) · 4 explotan por Rampa',
        setup: '4 Hall + 1 Secret',
        utilities: ['Smoke corta', 'Smoke larga', 'Smoke pasaje', 'Flash', 'Molotov'],
        tips: [
          '4 en Hall llegan a punto máximo → cuando el de afuera empieza a jugar → colapsan',
          'Ganar rampa con smoke: Flash → doble flash → moli Wizard',
          'El de Secret baja LENTO — ángulo por ángulo',
        ],
      },
    ],
  },
];

// Mapas adicionales del pool FACEIT (sin strats detalladas por ahora)
export const additionalMaps: MapDetail[] = [
  {
    id: 'inferno',
    name: 'Inferno',
    image: '/maps/inferno-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description: 'Mapa complejo con múltiples rutas. Requiere coordinación y control de información.',
    sideFavor: 'Balanced',
    callouts: {
      siteA: ['Bombsite A', 'Library', 'Apartments', 'Main'],
      siteB: ['Bombsite B', 'Banana', 'Graveyard'],
      middle: ['Underpass', 'Banana', 'Arch'],
    },
    fundamentals: {
      t: ['Coordinar entrada por aplicaciones', 'Controlar información'],
      ct: ['Defender posiciones defensivas', 'Mantener control de rotaciones'],
    },
    strats: [],
  },
  {
    id: 'vertigo',
    name: 'Vertigo',
    image: '/maps/vertigo-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description: 'Mapa vertical con alturas. El control de altura es crítico para ganar.',
    sideFavor: 'CT-sided',
    callouts: {
      siteA: ['Bombsite A', 'Rafters'],
      siteB: ['Bombsite B'],
      middle: ['Mid'],
    },
    fundamentals: {
      t: ['Usar altura a favor', 'Coordinar ataques'],
      ct: ['Defender desde posiciones altas', 'Rotar rápido'],
    },
    strats: [],
  },
  {
    id: 'ancient',
    name: 'Ancient',
    image: '/maps/ancient-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description: 'Mapa arqueológico con dos sites bien diferenciados y medio conectado.',
    sideFavor: 'Balanced',
    callouts: {
      siteA: ['Bombsite A', 'Main', 'Lobby'],
      siteB: ['Bombsite B', 'Water', 'Rafters'],
      middle: ['Mid', 'Plaza'],
    },
    fundamentals: {
      t: ['Ganar mid para abrir sites', 'Coordinar splits'],
      ct: ['Controlar mid', 'Rotas rápidas'],
    },
    strats: [],
  },
  {
    id: 'anubis',
    name: 'Anubis',
    image: '/maps/anubis-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description: 'Nuevo mapa con diseño complejo. Múltiples rutas y controlables.',
    sideFavor: 'Balanced',
    callouts: {
      siteA: ['Bombsite A', 'Main', 'Temple'],
      siteB: ['Bombsite B', 'Underpass'],
      middle: ['Mid', 'Plaza'],
    },
    fundamentals: {
      t: ['Explorar rutas alternativas', 'Obtener control de información'],
      ct: ['Defender múltiples entradas', 'Comunicación constante'],
    },
    strats: [],
  },
  {
    id: 'train',
    name: 'Train',
    image: '/maps/train-card.svg',
    calloutImage: '/maps/callout-bg.svg',
    description: 'Mapa de trenes con control de altas prioridades. El control de la entrada principal y vías es crítico para ambos lados.',
    sideFavor: 'Balanced',
    callouts: {
      siteA: ['Bombsite A', 'Inner', 'Hell', 'Popdog'],
      siteB: ['Bombsite B', 'Ivy', 'Rush', 'Connector'],
      middle: ['T Main', 'T Ladder', 'Upper'],
    },
    fundamentals: {
      t: ['Dominar Upper y Popdog', 'Forzar rotaciones con util'],
      ct: ['Controlar Inner y Connector', 'Mantener crossfires en Observatory'],
    },
    strats: [],
  },
];

export const allMaps = [...mapsData, ...additionalMaps];
