from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
MAP_ROOT = ROOT.parent / "maps"

CATEGORY_MAP = {
    "Retakes": "Retake",
}

MAPS = {
    "inferno": {
        "name": "Inferno",
        "sideFavor": "Balanced",
        "description": "Inferno exige control de banana y medio. La CT debe frenar avances tempranos y estar lista para retakes con smokes precisas.",
        "philosophy": {
            "philosophy": "Banana define la mayor parte de la ronda. Controlar banana y medio permite dictar dónde va a pelear el rival.",
            "tWinCondition": "Tomar banana o medio temprano y usar esa palanca para un split a A o un execute B planificado.",
            "ctWinCondition": "Negar banana con nades, retener medio y usar el retake cuando el T planta.",
            "keyAreas": ["Banana", "Mid", "A Site", "B Site", "Library"],
            "tempo": "Controlado con windows de agresión tras el tiempo 15-20s.",
            "rotationComplexity": "Alta: rotaciones entre CT y Mid requieren timing y comunicación constantes.",
        },
        "callouts": {
            "siteA": ["A Site", "Pit", "Truck", "Library", "Apartments"],
            "siteB": ["B Site", "Banana", "Coil", "Construction", "Second Oranges"],
            "middle": ["Mid", "Arch", "Short", "CT", "Second Mid"],
        },
        "fundamentals": {
            "t": [
                "Banana debe avanzar con trades; un banana libre cambia la ronda.",
                "El split A necesita Palace o Short para funcionar.",
            ],
            "ct": [
                "Los smokes de CT en Banana y Mid retrasan el execute.",
                "Un solo pick a través de Mid puede decidir la ronda.",
            ],
        },
        "defaults": [
            {
                "id": "inferno-default-2-1-2",
                "name": "Default 2-1-2",
                "category": "Default",
                "type": "default",
                "team": "T",
                "description": "Dos en banana, uno en medio y dos en A para leer y decidir.",
                "objectivePrincipal": "Conservar util y decidir site basado en la respuesta CT.",
                "concept": "No comprometerse sin información y aprovechar cualquier hueco en banana o A.",
                "risks": ["Perder banana temprano", "gastar util sin información"],
                "failReaction": "Si banana se pierde, pivotar a A con palace o a B con un rush rápido.",
                "adaptationsPossible": "Rotar un jugador desde A a Short si el CT está fuerte en banana.",
                "midRoundOptions": ["Split A", "Rush B", "Delay en banana"],
                "winCondition": "Llegar a 25s con ventaja numérica o util suficiente para ejecutar.",
                "failureStates": ["Banana perdido y A cerrado", "No hay rifles vivos."],
                "commonMistakes": ["Forzar sin trade", "mirar mucho sin avanzar"],
                "recoveryPlan": "Reagrupar y buscar el sitio que el CT dejó abierto.",
                "economyLogic": "Usar solo util clave para retener el tempo.",
                "minimumUtility": ["Smoke Banana", "Flash Mid"],
                "priorityWeapons": ["Rifle", "AWP en Mid"],
                "spacingRules": "Mantener trade cercano en Banana y A.",
                "utilityLayering": "Smoke Banana -> Flash Mid.",
                "timingWindows": "Decidir sobre el sitio entre 20-24s.",
                "reactionTree": "Banana libre -> B; medio roto -> A; todo contestado -> reset.",
                "rotationPunish": "Si el CT rota lento, explotar el sitio abandonado.",
                "lurkTiming": "El lurker espera 18s y luego corta la rotación.",
                "infoProtocols": "Reportar cuerpo en banana y presencia en Mid.",
                "setup": "2 Banana / 1 Mid / 2 A.",
                "playerDistribution": "Dos banana, uno mid, dos A.",
                "importantSpaces": ["Banana", "Pit", "Mid", "A Site"],
                "pointOfContact": "Banana primero, luego medio.",
                "postplant": "Cubrir bomb desde Pit y Library.",
                "roles": {
                    "entry": {
                        "position": "Banana",
                        "objective": "Ganar espacio y forzar la rotación de CT.",
                        "utility": "Flash de banana y humo de coil.",
                        "timing": "Iniciar el avance tras los primeros 10 segundos.",
                        "responsibility": "Abrir el contacto y absorber el primer fuego enemigo.",
                        "whatToLook": "Ángulos de banana, segundo oranges y coil.",
                        "communication": "\"Banana limpia / contacto banana\"",
                        "onTeammateDeath": "Avanzar con trade cercano y mantener la presión.",
                        "onNoContact": "Empujar un paso más y buscar información en medio.",
                        "postplant": "Cubrir plataforma y oranges desde banana.",
                    },
                    "support": {
                        "position": "Mid",
                        "objective": "Cubrir el avance de banana y asegurar que la CT no rote limpia.",
                        "utility": "Flash corto y smoke de mid.",
                        "timing": "Entrar tras el contacto inicial en banana.",
                        "responsibility": "Proveer trade y negar rotaciones desde CT.",
                        "whatToLook": "Movimiento en mid, CT en librería, rotación hacia B.",
                        "communication": "\"Mid control / rotación en camino\"",
                        "onTeammateDeath": "Cerrar mid y actuar como segundo trade.",
                        "onNoContact": "Avanzar hasta el banco para negar rotaciones.",
                        "postplant": "Cubrir árbol y librería desde mid.",
                    },
                },
            }
        ],
        "protocols": [
            {
                "id": "inferno-protocol-b-fake-a",
                "name": "Fake B / Execute A",
                "category": "Protocol",
                "type": "protocol",
                "team": "T",
                "description": "Presionar banana duro para atraer rotaciones y luego ejecutar A con advantage.",
                "objectivePrincipal": "Crear huecos en A usando la amenaza de B.",
                "concept": "Usar el fake de B para ganar medio y luego pasar a A.",
                "risks": ["CT no rota", "gastar util sin impacto"],
                "failReaction": "Si B queda intacto, reforzar B o volver a A con más calma.",
                "adaptationsPossible": "Split A con Palace si A se siente débil.",
                "midRoundOptions": ["Entrar A", "retener en B", "jugar sitio lento"],
                "winCondition": "A abierto con menos rotación en contra.",
                "failureStates": ["No se abre A", "B pierde sin cambio"],
                "commonMistakes": ["no comunicar el cambio", "usar util residual en el fake"],
                "recoveryPlan": "Volver a colocar la rotación en B o medio.",
                "economyLogic": "Conservar el humo para A.",
                "minimumUtility": ["Smoke Banana", "Flash A"],
                "priorityWeapons": ["Rifle", "AWP in Mid"],
                "spacingRules": "No agruparse en B durante el fake.",
                "utilityLayering": "Pressión B -> Smoke A.",
                "timingWindows": "Fake a 18s, cambio a 22s.",
                "reactionTree": "B reacciona -> A rápido; B no reacciona -> retener.",
                "rotationPunish": "Si el CT rota lento, castigar con util extra por B.",
                "lurkTiming": "Lurker de mid observa el cambio.",
                "infoProtocols": "Reportar smoke y contacto en B.",
                "setup": "3 B / 2 A.",
                "playerDistribution": "Tres B, dos A.",
                "importantSpaces": ["Banana", "Mid", "A Site"],
                "pointOfContact": "A después del fake.",
                "postplant": "Sostener desde Pit y Library.",
                "roles": {
                    "entry": {
                        "position": "Banana",
                        "objective": "Presionar y atraer la rotación enemiga.",
                        "utility": "Flash naranja y smoke banana.",
                        "timing": "Iniciar el fake en 18s.",
                        "responsibility": "Ser la primera amenaza que obliga a CT a reaccionar.",
                        "whatToLook": "Respuesta de CT en B y medio.",
                        "communication": "\"Fake B activo / cambio a A\"",
                        "onTeammateDeath": "Mantener la presión y no ceder terreno.",
                        "onNoContact": "Cambiar rápido a A con la util restante.",
                        "postplant": "Cubrir desde Pit si se planta en A.",
                    },
                },
            }
        ],
        "retakes": [
            {
                "id": "inferno-retake-b",
                "name": "Retake B",
                "category": "Retakes",
                "type": "retake",
                "team": "CT",
                "description": "Recuperar B con smoke de plataforma y flash de second oranges.",
                "objectivePrincipal": "Limpiar B con util y evitar trades perdidos.",
                "concept": "Tomar platform primero, luego retomar el site con crossfire.",
                "risks": ["No hay trade desde platform", "falla la smoke"],
                "failReaction": "Si el T planta rápido, resetear a la salida de Banana.",
                "adaptationsPossible": "Entrar por Construction si platform no es posible.",
                "midRoundOptions": ["Plant retake", "reset a Banana"],
                "winCondition": "B limpio y bomb sin plant o T muerto.",
                "failureStates": ["No hay smoke", "T planta con ventaja"],
                "commonMistakes": ["Entrar sin trade", "disparar a cuerpos sin limpiar ángulos"],
                "recoveryPlan": "Tomar la aproximación por Construction y volver a entrar.",
                "economyLogic": "Usar util crítica y guardar una smoke extra.",
                "minimumUtility": ["Smoke platform", "Flash oranges"],
                "priorityWeapons": ["Rifle platform", "SMG en Construction"],
                "spacingRules": "Entrar en columnas cortas.",
                "utilityLayering": "Smoke platform -> Flash oranges.",
                "timingWindows": "Iniciar retake a 22-25s.",
                "reactionTree": "Platform claro -> entrar; contestado -> resetear.",
                "rotationPunish": "Si el T rota de A, usar la línea de CT para cortar.",
                "lurkTiming": "Lurker se queda en platform hasta el primer trade.",
                "infoProtocols": "Reportar platform y oranges.",
                "setup": "2 Platform / 2 Construction / 1 Mid.",
                "playerDistribution": "Dos Platform, dos Construction, uno Mid.",
                "importantSpaces": ["Platform", "Oranges", "Construction"],
                "pointOfContact": "Platform.",
                "postplant": "Cubrir la planta desde Platform y Construction.",
                "roles": {
                    "anchor": {
                        "position": "Platform",
                        "objective": "Mantener la línea de retake y proteger la entrada.",
                        "utility": "Smoke platform y flash oranges.",
                        "timing": "Entrar tras limpiar platform con el apoyo del equipo.",
                        "responsibility": "Ser el último ángulo que retiene a B.",
                        "whatToLook": "Contacto en platform, oranges y construction.",
                        "communication": "\"Platform listo / entro en 3\"",
                        "onTeammateDeath": "Retener la posición y cubrir el hueco con util.",
                        "onNoContact": "Progresar lentamente y asegurar los ángulos uno por uno.",
                        "postplant": "Cubrir la planta desde platform y construction.",
                    },
                },
            }
        ],
        "reaggressions": [
            {
                "id": "inferno-reaggression-b",
                "name": "Reaggression Banana",
                "category": "Reaggression",
                "type": "reaggression",
                "team": "CT",
                "description": "Volver a presionar banana con flash y molotov tras perder el primer avance.",
                "objectivePrincipal": "Recuperar espacio y restaurar la línea de contención.",
                "concept": "Usar la velocidad y util para sorprender al T que no espera la agresión.",
                "risks": ["Quedar expuesto sin apoyo", "fallar los flashes"],
                "failReaction": "Si el T se repliega, cerrar banana y jugar el retake.",
                "adaptationsPossible": "Convertir a un control pasivo si el T se mantiene firme.",
                "midRoundOptions": ["Mantener banana", "rotar a A"],
                "winCondition": "Banana limpio de nuevo y el T forzado a jugar retrasado.",
                "failureStates": ["Banana perdido de nuevo", "CT sin trade"],
                "commonMistakes": ["Avanzar sin trade", "usar util demasiado rápido"],
                "recoveryPlan": "Cerrar banana y reorganizar para un retake.",
                "economyLogic": "Usar util justa para recuperar el hueco.",
                "minimumUtility": ["Flash banana", "Molotov top"],
                "priorityWeapons": ["Rifle banana", "SMG apoyo"],
                "spacingRules": "Entrar con líneas cortas y trade cercano.",
                "utilityLayering": "Flash banana -> Molotov top.",
                "timingWindows": "Hacer la re-agresión antes de 18s.",
                "reactionTree": "Banana claro -> empujar; contestado -> resetear.",
                "rotationPunish": "Si el T rota tarde, usar la presión para cortar su apoyo.",
                "lurkTiming": "El lurker de Mid puede apoyar solo tras el primer trade.",
                "infoProtocols": "Reportar apertura de banana y utilizaciones enemigas.",
                "setup": "3 Banana / 2 Mid.",
                "playerDistribution": "Tres Banana, dos Mid.",
                "importantSpaces": ["Banana", "Top", "Bottom"],
                "pointOfContact": "Banana.",
                "postplant": "Cubrir la planta desde Banana si el T ha plantado.",
                "roles": {
                    "rotator": {
                        "position": "Mid",
                        "objective": "Aportar apoyo rápido si banana se limpia.",
                        "utility": "Flash de medio y humo para negar rotación rápida.",
                        "timing": "Mantenerse listo para entrar tras el primer contacto.",
                        "responsibility": "Reforzar banana o girar hacia A según información.",
                        "whatToLook": "Movimientos en banana y posible cambio de A.",
                        "communication": "\"Banana limpio / rotación en camino\"",
                        "onTeammateDeath": "Cerrar el hueco dejado y frenar el avance enemigo.",
                        "onNoContact": "Mantener posición y esperar al trade.",
                        "postplant": "Cubrir desde Mid si el bomb se planta en B.",
                    },
                },
            }
        ],
        "antiEco": [
            {
                "id": "inferno-antico-b-tight",
                "name": "Anti-Eco B Tight Defense",
                "category": "Anti Eco",
                "type": "antiEco",
                "team": "CT",
                "description": "Cerrar B con líneas cortas y tradear al eco desde Van y Oranges.",
                "objectivePrincipal": "No permitir un plant barato y castigar entradas tempranas.",
                "concept": "Compactar la defensa y forzar al eco a exponerse.",
                "risks": ["Ser presionado por fuerza bruta", "no cubrir Market"],
                "failReaction": "Si el T rompe B, jugar el retake con smoke de Market.",
                "adaptationsPossible": "Mover un jugador a Mid si el eco se divide.",
                "midRoundOptions": ["Mantener B", "rotar apoyo a A"],
                "winCondition": "El eco no planta y pierde la ronda por trade.",
                "failureStates": ["B plantado fácilmente", "CT sin trade en plataforma"],
                "commonMistakes": ["exponerse demasiado", "no economizar util"],
                "recoveryPlan": "Ceder B y jugar un retake con util restante.",
                "economyLogic": "Usar util mínima y confiar en la posición.",
                "minimumUtility": ["Flash oranges", "Smoke Market"],
                "priorityWeapons": ["Rifle Van", "SMG Bench"],
                "spacingRules": "Líneas cerradas y trade cercano.",
                "utilityLayering": "Flash oranges -> Smoke Market.",
                "timingWindows": "Responder entre 8-18s.",
                "reactionTree": "B claro -> mantener; contestado -> reforzar.",
                "rotationPunish": "Si el T divide, castigar la linea libre.",
                "lurkTiming": "El lurker entra tras el primer trade.",
                "infoProtocols": "Informar bloques de B y Market.",
                "setup": "2 Van / 2 Oranges / 1 Mid.",
                "playerDistribution": "Dos Van, dos Oranges, uno Mid.",
                "importantSpaces": ["Van", "Oranges", "Market"],
                "pointOfContact": "Van.",
                "postplant": "Cubrir desde Van y Bench.",
                "roles": {
                    "anchor": {
                        "position": "Van",
                        "objective": "Ser la base de la defensa B y asegurar el primer trade.",
                        "utility": "Flash oranges y smoke Market.",
                        "timing": "Mantenerse en la línea hasta que el eco pruebe el sitio.",
                        "responsibility": "No dejar que el eco entre libremente a B.",
                        "whatToLook": "Nuevos flashes, entradas de túnel y movimientos por Market.",
                        "communication": "\"Van firme / necesita trade\"",
                        "onTeammateDeath": "Cortar la rotación y avisar la presión enemiga.",
                        "onNoContact": "Mantener la línea y no adelantarse sin información.",
                        "postplant": "Cubrir desde Van y Bench.",
                    },
                },
            }
        ],
        "pistol": [
            {
                "id": "inferno-pistol-t-b-rush",
                "name": "Pistol Rush B",
                "category": "Pistol",
                "type": "pistol",
                "team": "T",
                "description": "Cargar Banana con flashes rápidos y plant costoso en B.",
                "objectivePrincipal": "Ganar B antes de que el CT tenga util.",
                "concept": "Velocidad, flash y trade cercano.",
                "risks": ["Mala sincronía en flashes", "CT en platform"],
                "failReaction": "Si el CT está fuerte, plantar barato cerca del Car.",
                "adaptationsPossible": "Cambiar a un rush A si banana está cerrada.",
                "midRoundOptions": ["Plantar B", "apoyar un postplant estándar"],
                "winCondition": "Bomb plantado y dos cruces claras.",
                "failureStates": ["Perder la ronda en Banana"],
                "commonMistakes": ["Flashear fuera de tiempo", "entrar separados"],
                "recoveryPlan": "Jugar el postplant de B con el arma restante.",
                "economyLogic": "Gastar util mínima y máxima movilidad.",
                "minimumUtility": ["Flash banana", "Smoke cave"],
                "priorityWeapons": ["Pistolas fuertes", "SMG si hay"],
                "spacingRules": "Mantener grupos pequeños.",
                "utilityLayering": "Flash banana -> Smoke cave.",
                "timingWindows": "Entrar a 18-20s.",
                "reactionTree": "Banana claro -> empujar; contestado -> plantear.",
                "rotationPunish": "Si el CT rota de A, usar banana para castigar.",
                "lurkTiming": "El lurker va a cave tras el primer trade.",
                "infoProtocols": "Reportar platform y cave.",
                "setup": "5 B.",
                "playerDistribution": "Todos en Banana.",
                "importantSpaces": ["Banana", "Cave", "Platform"],
                "pointOfContact": "Banana.",
                "postplant": "Cubrir desde Platform y Car.",
                "roles": {
                    "entry": {
                        "position": "Banana",
                        "objective": "Abrir la línea principal y obligar a gastar util.",
                        "utility": "Flash a platform y smoke cave.",
                        "timing": "Entrar agresivo a 18-20s.",
                        "responsibility": "Ser la primera presión y absorber el primer fuego.",
                        "whatToLook": "Platform, cave y amarillo.",
                        "communication": "\"Banana listo / flash arriba\"",
                        "onTeammateDeath": "Avanzar con el segundo entry y cubrir el ángulo.",
                        "onNoContact": "Acelerar hacia el sitio y plantar rápido.",
                        "postplant": "Cubrir desde Platform y Car.",
                    },
                },
            }
        ],
        "eco": [
            {
                "id": "inferno-eco-mid-pick",
                "name": "Eco Mid Pick",
                "category": "Eco",
                "type": "eco",
                "team": "T",
                "description": "Jugar medio con un rifle para robar un arma o escalar ventaja.",
                "objectivePrincipal": "Obtener un pick que permita un giro rápido de la ronda.",
                "concept": "Presión controlada desde Arch mientras se respeta el trade.",
                "risks": ["Ser flanqueado", "no conseguir pick"],
                "failReaction": "Si no hay pick, retirarse y jugar un sitio barato.",
                "adaptationsPossible": "Rotar a B si el CT abandona banana.",
                "midRoundOptions": ["Seguir mid", "push a A"],
                "winCondition": "Pick conseguido y equipo con ventaja de arma.",
                "failureStates": ["Desperdiciar el rifle comprado"],
                "commonMistakes": ["Forzar el duelo sin trade"],
                "recoveryPlan": "Retirarse a una posición segura con el arma restante.",
                "economyLogic": "Conservar el rifle y no gastar util.",
                "minimumUtility": ["Flash Mid"],
                "priorityWeapons": ["Rifle económico"],
                "spacingRules": "Mantener líneas cortas.",
                "utilityLayering": "Flash Mid.",
                "timingWindows": "Buscar el pick a 18-20s.",
                "reactionTree": "Pick -> empujar; sin pick -> replegar.",
                "rotationPunish": "Si rota mal, explotar A o B.",
                "lurkTiming": "El lurker de A recorta tras el pick.",
                "infoProtocols": "Reportar movimientos en Mid y Arch.",
                "setup": "2 Mid / 3 A/B.",
                "playerDistribution": "Dos Mid, tres de apoyo.",
                "importantSpaces": ["Mid", "Arch", "CT"],
                "pointOfContact": "Mid.",
                "postplant": "Ajustar al arma y la planta segura.",
                "roles": {
                    "awper": {
                        "position": "Mid",
                        "objective": "Controlar el largo y atrapar rotaciones.",
                        "utility": "Flash de recuperación si hay múltiples enemigos.",
                        "timing": "Esperar hasta ver la primera pista de movimiento.",
                        "responsibility": "Ser la pieza clave para robar información.",
                        "whatToLook": "Arch, Short y CT mid.",
                        "communication": "\"AWP mid listo / pick pendiente\"",
                        "onTeammateDeath": "Reubicar y mantener la línea de mid.",
                        "onNoContact": "Avanzar con cautela y buscar el trade.",
                        "postplant": "Cubrir la rotación larga desde mid.",
                    },
                },
            }
        ],
        "force": [
            {
                "id": "inferno-force-b-early",
                "name": "Force B Early",
                "category": "Force Buy",
                "type": "force",
                "team": "T",
                "description": "Entrar B rápido con SMGs y flashes para aprovechar una defensiva CT débil.",
                "objectivePrincipal": "Obtener el sitio antes de que el CT se establezca.",
                "concept": "Velocidad y trade corto sobre control de util.",
                "risks": ["Flash mal sincronizado", "upper cerrado"],
                "failReaction": "Si se pierde el primer contacto, plantar con el resto y jugar postplant.",
                "adaptationsPossible": "Rotar a A si B se cierra completamente.",
                "midRoundOptions": ["Plantar B", "jugar una segunda línea"],
                "winCondition": "B plantado con ventaja de trade.",
                "failureStates": ["T pierde la mayoría antes de entrar"],
                "commonMistakes": ["asomarse solo", "no coordinar flashes"],
                "recoveryPlan": "Desplegar el postplant con el humo restante.",
                "economyLogic": "Usar util mínima y priorizar peso de arma corta.",
                "minimumUtility": ["Flash B", "Smoke Market"],
                "priorityWeapons": ["SMG en Banana", "Rifle en Van"],
                "spacingRules": "Grupo compacto con trade cercano.",
                "utilityLayering": "Flash B -> Smoke Market.",
                "timingWindows": "Entrar antes del 18s.",
                "reactionTree": "B libre -> empujar; contestado -> plantar.",
                "rotationPunish": "Si el CT rota de A, usar Market para cortar.",
                "lurkTiming": "El lurker entra tras el primer contacto.",
                "infoProtocols": "Reportar platform y Market.",
                "setup": "5 B.",
                "playerDistribution": "Todos en Banana.",
                "importantSpaces": ["Banana", "B Site", "Market"],
                "pointOfContact": "Banana.",
                "postplant": "Retener desde Market y Van.",
                "roles": {
                    "entry": {
                        "position": "Banana",
                        "objective": "Forzar el contacto temprano y abrir el sitio B.",
                        "utility": "Flash de entrada y humo de Market.",
                        "timing": "Entrada rápida antes de los 18s.",
                        "responsibility": "Ser el primer impacto y asegurar trade.",
                        "whatToLook": "Platform, Market y Secret.",
                        "communication": "\"Rush B / flash listo\"",
                        "onTeammateDeath": "Mantener el impulso y plantar si es posible.",
                        "onNoContact": "Avanzar hacia la planta y usar el humo restante.",
                        "postplant": "Cubrir desde Market y Van.",
                    },
                },
            }
        ],
        "buy": [
            {
                "id": "inferno-buy-a-exec",
                "name": "Full A Execute",
                "category": "Full Buy",
                "type": "buy",
                "team": "T",
                "description": "Ejecutar A con smokes de Library y Pit, apoyado por Palace y Short.",
                "objectivePrincipal": "Tomar A con control total y planta segura en Puerta.",
                "concept": "Aislar el sitio con util y obligar al CT a jugar bajo presión.",
                "risks": ["Fallas de smoke", "Short aún fuerte"],
                "failReaction": "Si no se abre, plantar barato y jugar postplant en Puerta.",
                "adaptationsPossible": "Split A con Short si Library está bloqueado.",
                "midRoundOptions": ["Plantar rápido", "reajustar a Short con más smokes"],
                "winCondition": "A con cruz limpia y planta protegida.",
                "failureStates": ["A cerrado sin plant", "bomb plant con mal ángulo"],
                "commonMistakes": ["avanzar sin trade", "no cubrir Short"],
                "recoveryPlan": "Replegar a la Puerta y jugar un plant seguro.",
                "economyLogic": "Invertir en util clave y rifles.",
                "minimumUtility": ["Smoke Library", "Smoke Pit", "Flash Short"],
                "priorityWeapons": ["Rifle en Palace", "AWP en Mid"],
                "spacingRules": "Mantener líneas de trade para cada ángulo.",
                "utilityLayering": "Smoke Library -> Smoke Pit -> Flash Short.",
                "timingWindows": "Ejecutar a 22-24s.",
                "reactionTree": "A claro -> empujar; A contestado -> plantear.",
                "rotationPunish": "Si el CT rota de B, usar Palace para cortar.",
                "lurkTiming": "El lurker de Short apoya después del primer trade.",
                "infoProtocols": "Reportar Short, Palace y Library.",
                "setup": "2 Palace / 2 Short / 1 Mid.",
                "playerDistribution": "Dos Palace, dos Short, uno Mid.",
                "importantSpaces": ["Palace", "Short", "Pit", "A Site"],
                "pointOfContact": "Short y Palace.",
                "postplant": "Cubrir desde Pit y Library.",
                "roles": {
                    "support": {
                        "position": "Short",
                        "objective": "Proveer util y trade para el execute A.",
                        "utility": "Flash Short y smoke Library.",
                        "timing": "Sincronizar el apoyo con la entrada principal.",
                        "responsibility": "Mantener la línea de trade y asegurar el sitio.",
                        "whatToLook": "Short, Library y Palace.",
                        "communication": "\"Short listo / smoke library\"",
                        "onTeammateDeath": "Cerrar el hueco y mantener el sitio.",
                        "onNoContact": "Avanzar con cuidado y apoyar la planta.",
                        "postplant": "Cubrir desde Short y Library.",
                    },
                },
            }
        ],
        "midRound": [
            {
                "id": "inferno-midround-b-split",
                "name": "Mid Round B Split",
                "category": "Mid Round",
                "type": "midRound",
                "team": "T",
                "description": "Cambiar a B desde Mid y Apps cuando la defensa CT se despliega hacia A.",
                "objectivePrincipal": "Aprovechar las rotaciones del CT para abrir B.",
                "concept": "Sumar presión desde Mid y Apartments al mismo tiempo.",
                "risks": ["CT no rota", "B se vuelve más fuerte"],
                "failReaction": "Si B no se abre, volver a A con la util restante.",
                "adaptationsPossible": "Transformar en un rush B clásico si el CT es débil en Apps.",
                "midRoundOptions": ["Entrar B", "resituar a A"],
                "winCondition": "B con control de Van y Market.",
                "failureStates": ["CT demasiado firme en B"],
                "commonMistakes": ["moverse sin trade", "no cubrir Market"],
                "recoveryPlan": "Retirarse a Apartments y esperar la segunda fase.",
                "economyLogic": "Usar util clave para el split y guardar lo esencial.",
                "minimumUtility": ["Smoke Market", "Flash Apps"],
                "priorityWeapons": ["Rifle en Mid", "AWP en Short"],
                "spacingRules": "Entrar en dos líneas con trade cercano.",
                "utilityLayering": "Smoke Market -> Flash Apps.",
                "timingWindows": "Cambiar a B tras 18s de lectura.",
                "reactionTree": "B libre -> empujar; B contestado -> resetear.",
                "rotationPunish": "Si el CT rota mal, castigar desde Mid.",
                "lurkTiming": "El lurker de Apartments entra si B está vacío.",
                "infoProtocols": "Reportar Van y Market abiertos.",
                "setup": "2 Mid / 3 B.",
                "playerDistribution": "Dos Mid, tres B.",
                "importantSpaces": ["Mid", "Apps", "Market"],
                "pointOfContact": "Van y Market.",
                "postplant": "Cubrir desde Van y Bench.",
                "roles": {
                    "rotator": {
                        "position": "Mid",
                        "objective": "Cortar rotaciones y apoyar el split B.",
                        "utility": "Flash Apps y smoke Market.",
                        "timing": "Entrar tras evaluar la respuesta de A.",
                        "responsibility": "Asegurar la segunda línea de presión.",
                        "whatToLook": "Market, Van y apartamentos.",
                        "communication": "\"Mid listo / B en camino\"",
                        "onTeammateDeath": "Mantener la línea central y cubrir el hueco.",
                        "onNoContact": "Progresar lentamente y preparar el site.",
                        "postplant": "Cubrir desde Van y Bench.",
                    },
                },
            }
        ],
    },
    "nuke": {
        "name": "Nuke",
        "sideFavor": "CT-sided",
        "description": "Nuke premia control vertical. La CT debe maximizar sus ángulos y minimizar la información que pierde en ramps.",
        "philosophy": {
            "philosophy": "Controlar ramp, squeaky y vent es la columna vertebral CT. El T debe forzar rotaciones y aislar los sitios.",
            "tWinCondition": "Crear una secundaria presencia en ramp o vent para dividir la defensa.",
            "ctWinCondition": "Mantener las escaleras y castigar cualquier push rápido con AWPs y smokes de rotación.",
            "keyAreas": ["Ramp", "Squeaky", "Heaven", "Hut", "Yard"],
            "tempo": "Ritmo rápido en ataque, paciente en defensa.",
            "rotationComplexity": "Alta: múltiples alturas y líneas de visión simultáneas.",
        },
        "callouts": {
            "siteA": ["A Site", "Squeaky", "Heaven", "Hut", "Ramp"],
            "siteB": ["B Site", "Yard", "Silo", "Hell", "Secret"],
            "middle": ["Lobby", "Vent", "Outside", "Backyard", "Spawn"],
        },
        "fundamentals": {
            "t": [
                "Buscar la pieza aislada entre ramp y vent.",
                "No perder la utilidad clave en lobby.",
            ],
            "ct": [
                "No pelear ramp sin rotación.",
                "Usar antistall smoke en vent en el sitio B.",
            ],
        },
        "defaults": [
            {
                "id": "nuke-default-ramp-split",
                "name": "Default Ramp Split",
                "category": "Default",
                "type": "default",
                "team": "T",
                "description": "Presión desplegada entre ramp y vent para forzar swaps CT.",
                "objectivePrincipal": "Leer si la CT abandona A o B.",
                "concept": "Custodiar la información y luego empujar el sitio débil.",
                "risks": ["CT se atrinchera en vent", "pérdida de ramp inicial"],
                "failReaction": "Retroceder a yard si la CT cierra A.",
                "adaptationsPossible": "Volcar a B si A está muy congestionado.",
                "midRoundOptions": ["Split A", "Rush B"],
                "winCondition": "Ganar control vertical y ejecutar con util.",
                "failureStates": ["Batalla de trades perdidos"],
                "commonMistakes": ["forzar sin trade", "olvidar vent"],
                "recoveryPlan": "Aislar a la CT en Out o Secret.",
                "economyLogic": "Conservar nades para la ejecución.",
                "minimumUtility": ["Smoke Ramp", "Smoke Squeaky"],
                "priorityWeapons": ["Rifle", "AWP en Outside"],
                "spacingRules": "Dos líneas de trade en Ramp y Vent.",
                "utilityLayering": "Smoke Ramp -> Flash Squeaky.",
                "timingWindows": "Decidir el sitio a 18s.",
                "reactionTree": "A libre -> ejecutar; A contestado -> girar B.",
                "rotationPunish": "Si la CT gira lento, golpear B rápido.",
                "lurkTiming": "Lurker en Outside espera la rotación.",
                "infoProtocols": "Reportar ramp y squeaky.",
                "setup": "2 Ramp / 2 Outside / 1 Vent.",
                "playerDistribution": "Dos Ramp, dos Outside, uno Vent.",
                "importantSpaces": ["Ramp", "Squeaky", "Outside", "Vent"],
                "pointOfContact": "Ramp y Vent.",
                "postplant": "Cubrir desde Heaven y Hut.",
                "roles": {
                    "entry": {
                        "position": "Ramp",
                        "objective": "Tomar el espacio inicial y forzar la rotación.",
                        "utility": "Smoke Ramp y flash Squeaky.",
                        "timing": "Avanzar tras recibir información de Lobby.",
                        "responsibility": "Ser el primer contacto y abrir la ruta a A.",
                        "whatToLook": "Lobby, Outside y Vent.",
                        "communication": "\"Ramp listo / rotación pendiente\"",
                        "onTeammateDeath": "Mantener el avance y no ceder la posición.",
                        "onNoContact": "Acelerar hacia A o vent según el plan.",
                        "postplant": "Cubrir desde Ramp y Heaven.",
                    },
                },
            }
        ],
        "protocols": [
            {
                "id": "nuke-protocol-outside-b",
                "name": "Outside Pressure B",
                "category": "Protocol",
                "type": "protocol",
                "team": "T",
                "description": "Forzar a la CT a gastar util en outside para abrir el B más tarde.",
                "objectivePrincipal": "Provocar rotaciones y ganar espacio en yard.",
                "concept": "Presionar outside sin comprometer inmediatamente el sitio.",
                "risks": ["CT aguanta outside fuerte", "perder lobby"],
                "failReaction": "Si la CT resiste, girar a A por ramp.",
                "adaptationsPossible": "Convertir en un rush B si hay hueco en yard.",
                "midRoundOptions": ["Plantar B tarde", "rotar a A"],
                "winCondition": "B con menos rotaciones en contra.",
                "failureStates": ["CT intacta en B"],
                "commonMistakes": ["exponerse sin trade", "no proteger yard"],
                "recoveryPlan": "Reforzar ramp y jugar A o un postplant B.",
                "economyLogic": "Guardar dos smokes para B.",
                "minimumUtility": ["Smoke Yard", "Flash Outside"],
                "priorityWeapons": ["AWP Outside", "Rifle Ramp"],
                "spacingRules": "Dividir líneas entre Outside y Lobby.",
                "utilityLayering": "Smoke Yard -> Flash Outside.",
                "timingWindows": "Mantener la presión hasta 22s.",
                "reactionTree": "B abierto -> ejecutar; B cerrado -> girar A.",
                "rotationPunish": "Si la CT rota mal, explotar el sitio sin cobertura.",
                "lurkTiming": "Lurker en Vent entra si hay rotación baja.",
                "infoProtocols": "Reportar daño en outside y yard.",
                "setup": "3 Outside / 2 Lobby.",
                "playerDistribution": "Tres Outside, dos Lobby.",
                "importantSpaces": ["Outside", "Yard", "Vent"],
                "pointOfContact": "Yard y Outside.",
                "postplant": "Cubrir desde Silo y Secret.",
                "roles": {
                    "support": {
                        "position": "Outside",
                        "objective": "Presionar yard y negar la rotación B.",
                        "utility": "Flash Outside y smoke Yard.",
                        "timing": "Sincronizar el apoyo con el avance inicial.",
                        "responsibility": "Mantener a la CT incómoda sin abrir B de inmediato.",
                        "whatToLook": "Silo, Secret y Lobby.",
                        "communication": "\"Outside presionado / B posible\"",
                        "onTeammateDeath": "Cerrar la línea y proteger la rotación.",
                        "onNoContact": "Continuar la presión sin exponerse.",
                        "postplant": "Cubrir desde Silo y Secret.",
                    },
                },
            }
        ],
        "retakes": [
            {
                "id": "nuke-retake-b",
                "name": "Retake B",
                "category": "Retakes",
                "type": "retake",
                "team": "CT",
                "description": "Recuperar B con humo de Silo y control de Secret.",
                "objectivePrincipal": "Limpiar B con util y trade eficiente.",
                "concept": "Asegurar Secret primero y luego entrar con humo.",
                "risks": ["Pérdida de Secret", "falla de smoke"],
                "failReaction": "Si Secret no se limpia, esperar una segunda oportunidad.",
                "adaptationsPossible": "Usar Ramp para cortar rotación.",
                "midRoundOptions": ["Retake B", "resetear a Outside"],
                "winCondition": "B limpio con el site cerrado.",
                "failureStates": ["T planta con ventaja"],
                "commonMistakes": ["entrar sin Secret limpio", "usar toda la util de una vez"],
                "recoveryPlan": "Tomar una posición defensiva en Outside.",
                "economyLogic": "Usar util clave y conservar una smoke.",
                "minimumUtility": ["Smoke Silo", "Flash Secret"],
                "priorityWeapons": ["Rifle Secret", "AWP Heaven"],
                "spacingRules": "Entrar en columnas estrechas.",
                "utilityLayering": "Smoke Silo -> Flash Secret.",
                "timingWindows": "Empezar a 22-24s.",
                "reactionTree": "Secret limpio -> entrar; contestado -> resetear.",
                "rotationPunish": "Si el T rota a A, usar la altura de Heaven para cortar.",
                "lurkTiming": "Lurker se mantiene en Hell para trade.",
                "infoProtocols": "Reportar Secret y B Site.",
                "setup": "2 Heaven / 2 Secret / 1 Ramp.",
                "playerDistribution": "Dos Heaven, dos Secret, uno Ramp.",
                "importantSpaces": ["Silo", "Secret", "B Site"],
                "pointOfContact": "Secret.",
                "postplant": "Cubrir desde Heaven y Secret.",
                "roles": {
                    "anchor": {
                        "position": "Secret",
                        "objective": "Mantener la línea de retake desde Secret.",
                        "utility": "Flash Secret y smoke Silo.",
                        "timing": "Entrar solo tras limpiar Secret.",
                        "responsibility": "Proteger el acceso a B y frenar al T.",
                        "whatToLook": "Silo, Hell y rotaciones desde Ramp.",
                        "communication": "\"Secret listo / entro\"",
                        "onTeammateDeath": "Cobrar la posición y evitar que el sitio se caiga.",
                        "onNoContact": "Mantener la línea y esperar al trade.",
                        "postplant": "Cubrir desde Secret y Heaven.",
                    },
                },
            }
        ],
        "reaggressions": [
            {
                "id": "nuke-reaggression-ramp",
                "name": "Reaggression Ramp",
                "category": "Reaggression",
                "type": "reaggression",
                "team": "CT",
                "description": "Volver a tomar Ramp con util después de cederlo temporalmente.",
                "objectivePrincipal": "Recuperar la altura y la escalera de rotación.",
                "concept": "Entrar rápido con flash y molotov para sorprender al T.",
                "risks": ["No trade suficiente", "exponer Heaven"],
                "failReaction": "Si falla, estabilizar en Hut y Heaven.",
                "adaptationsPossible": "Dejar un jugador en Ramp y cerrar A.",
                "midRoundOptions": ["Mantener Ramp", "rotar a A"],
                "winCondition": "Ramp recuperado y el T sin control exterior.",
                "failureStates": ["Ramp retenido por el T"],
                "commonMistakes": ["Volver sin trade", "usar util mal"],
                "recoveryPlan": "Replegar a Hut y Heaven.",
                "economyLogic": "Usar util de forma selectiva.",
                "minimumUtility": ["Flash Ramp", "Molotov Lobby"],
                "priorityWeapons": ["Rifle Ramp", "SMG Hut"],
                "spacingRules": "Ingresar en columnas cerradas.",
                "utilityLayering": "Flash Ramp -> Molotov Lobby.",
                "timingWindows": "Hacerlo antes de 18s si el T domina Ramp.",
                "reactionTree": "Ramp claro -> empujar; contestado -> resetear.",
                "rotationPunish": "Si el T rota a B, usar Heaven para cortar.",
                "lurkTiming": "Lurker en Outside espera la rotación.",
                "infoProtocols": "Reportar Ramp y Lobby.",
                "setup": "2 Ramp / 2 Hut / 1 Heaven.",
                "playerDistribution": "Dos Ramp, dos Hut, uno Heaven.",
                "importantSpaces": ["Ramp", "Squeaky", "Lobby"],
                "pointOfContact": "Ramp.",
                "postplant": "Cubrir desde Heaven y Hut.",
                "roles": {
                    "rotator": {
                        "position": "Ramp",
                        "objective": "Aportar apoyo rápido tras la recuperación.",
                        "utility": "Flash Ramp y molotov Lobby.",
                        "timing": "Entrar tras el primer trade.",
                        "responsibility": "Cerrar el espacio y mantener la línea.",
                        "whatToLook": "Lobby, Vent y outside.",
                        "communication": "\"Ramp otra vez / entro\"",
                        "onTeammateDeath": "Reagruparse y fijar la posición.",
                        "onNoContact": "Avanzar con cuidado y asegurar Ramp.",
                        "postplant": "Cubrir desde Heaven y Hut.",
                    },
                },
            }
        ],
        "antiEco": [
            {
                "id": "nuke-antico-outside",
                "name": "Anti-Eco Outside Setup",
                "category": "Anti Eco",
                "type": "antiEco",
                "team": "CT",
                "description": "Cortar el eco en outside con líneas cerradas y trade cercano.",
                "objectivePrincipal": "Evitar que planten barato y forzar errores de toma de decisiones.",
                "concept": "Enviar a un jugador por Secret y otro por Outside line para cubrir rotaciones.",
                "risks": ["Ser divididos", "perder fuera sin trade"],
                "failReaction": "Si el eco entra en B, cerrar Secret y jugar retake.",
                "adaptationsPossible": "Reforzar Secret si outside es sobrepasado.",
                "midRoundOptions": ["Cerrar Outside", "jugar más profundo"],
                "winCondition": "El eco no planta y se pierde por trade.",
                "failureStates": ["B plantado barato"],
                "commonMistakes": ["jugar muy adelantado", "no traducir la información"],
                "recoveryPlan": "Ceder yard y jugar un retake B con util.",
                "economyLogic": "Usar util de forma selectiva y económica.",
                "minimumUtility": ["Flash Outside", "Smoke Yard"],
                "priorityWeapons": ["Rifle Outside", "SMG Secret"],
                "spacingRules": "Mantener líneas cerradas.",
                "utilityLayering": "Flash Outside -> Smoke Yard.",
                "timingWindows": "Responder entre 10-18s.",
                "reactionTree": "Outside claro -> mantener; contestado -> resetear.",
                "rotationPunish": "Si el eco divide, castigar la línea más ligera.",
                "lurkTiming": "El lurker se mantiene en Secret para trade.",
                "infoProtocols": "Reportar presencia en Outside.",
                "setup": "2 Outside / 1 Secret / 2 Ramp.",
                "playerDistribution": "Dos Outside, uno Secret, dos Ramp.",
                "importantSpaces": ["Outside", "Yard", "Secret"],
                "pointOfContact": "Outside.",
                "postplant": "Cubrir desde Silo y Heaven.",
                "roles": {
                    "support": {
                        "position": "Outside",
                        "objective": "Mantener la línea de outside y negar el eco.",
                        "utility": "Flash Outside y smoke Yard.",
                        "timing": "Responder rápido a la entrada del eco.",
                        "responsibility": "Forzar al eco a exponerse y gastar util.",
                        "whatToLook": "Yard, Silo y Secret.",
                        "communication": "\"Outside bloqueado / eco presente\"",
                        "onTeammateDeath": "Cerrar la línea y mantener la presión.",
                        "onNoContact": "Mantenerse en la línea y asegurar rotación.",
                        "postplant": "Cubrir desde Silo y Heaven.",
                    },
                },
            }
        ],
        "pistol": [
            {
                "id": "nuke-pistol-ramp-split",
                "name": "Pistol Ramp Split",
                "category": "Pistol",
                "type": "pistol",
                "team": "T",
                "description": "Empujar ramp con trade cercano y presencia secundaria en vent.",
                "objectivePrincipal": "Forzar a la CT a abrir A con poca util.",
                "concept": "Velocidad y múltiples líneas de fuego.",
                "risks": ["Perder ramp sin trade", "vent expuesto"],
                "failReaction": "Si está cerrada, girar a B con el arma restante.",
                "adaptationsPossible": "Reagruparse en Lobby.",
                "midRoundOptions": ["Plantar A", "rotar B"],
                "winCondition": "A plantado con ventaja de trade.",
                "failureStates": ["CT demasiado firme en ramp"],
                "commonMistakes": ["asomarse solos", "no usar flashes"],
                "recoveryPlan": "Tomar una posición cómoda y jugar el plant.",
                "economyLogic": "Conservar lo mínimo necesario.",
                "minimumUtility": ["Flash Ramp"],
                "priorityWeapons": ["SMG", "Pistola con penetración"],
                "spacingRules": "Trade cercano y compacto.",
                "utilityLayering": "Flash Ramp.",
                "timingWindows": "Abrir a 18-20s.",
                "reactionTree": "Ramp libre -> empujar; contestado -> rotar.",
                "rotationPunish": "Si el CT rota a B, explotar ganador en yard.",
                "lurkTiming": "Lurker en Vent espera la rotación.",
                "infoProtocols": "Reportar daño en ramp.",
                "setup": "3 Ramp / 2 Vent.",
                "playerDistribution": "Tres Ramp, dos Vent.",
                "importantSpaces": ["Ramp", "Vent", "A Site"],
                "pointOfContact": "Ramp.",
                "postplant": "Cubrir desde Squeaky y Heaven.",
                "roles": {
                    "entry": {
                        "position": "Ramp",
                        "objective": "Abrir la línea hacia A.",
                        "utility": "Flash Ramp.",
                        "timing": "Entrar tras el primer contacto.",
                        "responsibility": "Ser el primer impacto y absorber el fuego enemigo.",
                        "whatToLook": "Lobby, Heaven y Squeaky.",
                        "communication": "\"Ramp listo / flash\"",
                        "onTeammateDeath": "Mantener la presión y cubrir el segundo paso.",
                        "onNoContact": "Avanzar hacia A y plantar si es posible.",
                        "postplant": "Cubrir desde Heaven y Hut.",
                    },
                },
            }
        ],
        "eco": [
            {
                "id": "nuke-eco-secret",
                "name": "Eco Secret Push",
                "category": "Eco",
                "type": "eco",
                "team": "T",
                "description": "Intentar atrapar a la defensa en Secret antes de que se consolide.",
                "objectivePrincipal": "Obtener un arma o una rotación mal gestionada.",
                "concept": "Presión temprana con mínima util.",
                "risks": ["Ser flanqueado por Secret", "quedar fuera de sitio"],
                "failReaction": "Si fallan, recular y evitar el compromiso.",
                "adaptationsPossible": "Volver a Outside y forzar el sitio B.",
                "midRoundOptions": ["Seguir Secret", "retirarse a Outside"],
                "winCondition": "Arma recuperada o rotación ganada.",
                "failureStates": ["Secret neutralizada"],
                "commonMistakes": ["entrar sin trade", "no cubrir la rotación"],
                "recoveryPlan": "Reagruparse y jugar un sitio seguro.",
                "economyLogic": "Conservar el rifle y la util restante.",
                "minimumUtility": ["Flash Secret"],
                "priorityWeapons": ["Rifle económico"],
                "spacingRules": "Entrar juntos.",
                "utilityLayering": "Flash Secret.",
                "timingWindows": "Hacerlo antes del 20s.",
                "reactionTree": "Secret libre -> empujar; contestado -> retirarse.",
                "rotationPunish": "Si gira mal, explotar B.",
                "lurkTiming": "Lurker en Outside vigila la rotación.",
                "infoProtocols": "Reportar pasos en Secret.",
                "setup": "3 Secret / 2 Outside.",
                "playerDistribution": "Tres Secret, dos Outside.",
                "importantSpaces": ["Secret", "Outside", "B Site"],
                "pointOfContact": "Secret.",
                "postplant": "Retirar el arma restante con cuidado.",
                "roles": {
                    "lurker": {
                        "position": "Outside",
                        "objective": "Asegurar información y cortar rotaciones.",
                        "utility": "Flash Outside.",
                        "timing": "Mantenerse retrasado hasta la fase de push.",
                        "responsibility": "Ser la bala extra si el CT rota.",
                        "whatToLook": "Yard, Silo y Secret.",
                        "communication": "\"Outside listo / Secret en camino\"",
                        "onTeammateDeath": "Apoyar el sitio y mantener el control del pasillo.",
                        "onNoContact": "Avanzar con cuidado y asegurar el ángulo.",
                        "postplant": "Cubrir desde Outside y Secret.",
                    },
                },
            }
        ],
        "force": [
            {
                "id": "nuke-force-b-press",
                "name": "Force B Press",
                "category": "Force Buy",
                "type": "force",
                "team": "T",
                "description": "Apostar a yard rápido con SMGs y usar el humo para entrar en B.",
                "objectivePrincipal": "Abrir B con presión que la CT no pueda sostener.",
                "concept": "Velocidad y líneas de trade cercanas.",
                "risks": ["Smoke mal colocado", "Secret no despejada"],
                "failReaction": "Si B está cerrada, plantar barato y jugar el postplant.",
                "adaptationsPossible": "Reagruparse en Outside.",
                "midRoundOptions": ["Plantar B", "retirarse a A"],
                "winCondition": "B plantado y retener la rotación.",
                "failureStates": ["T fuera de posición"],
                "commonMistakes": ["entrar sin trade", "olvidar el humo de yard"],
                "recoveryPlan": "Cubrir la planta desde Silo.",
                "economyLogic": "Gastar util mínima y priorizar velocidad.",
                "minimumUtility": ["Smoke Yard", "Flash B"],
                "priorityWeapons": ["SMG", "Rifle corto"],
                "spacingRules": "Trade cercano y compacto.",
                "utilityLayering": "Smoke Yard -> Flash B.",
                "timingWindows": "Entrar antes del 18s.",
                "reactionTree": "Yard claro -> empujar; contestado -> retroceder.",
                "rotationPunish": "Si CT rota mal, explotar A/vía secundaria.",
                "lurkTiming": "Lurker en Secret apoya tras el primer trade.",
                "infoProtocols": "Reportar Silo y Hell.",
                "setup": "3 Yard / 2 Secret.",
                "playerDistribution": "Tres Yard, dos Secret.",
                "importantSpaces": ["Yard", "Silo", "B Site"],
                "pointOfContact": "Yard.",
                "postplant": "Retener desde Silo y Heaven.",
                "roles": {
                    "entry": {
                        "position": "Yard",
                        "objective": "Abrir la ruta hacia B.",
                        "utility": "Flash B y smoke Yard.",
                        "timing": "Entrar rápido con el primer impulso.",
                        "responsibility": "Ser el primer contacto y asegurar la entrada.",
                        "whatToLook": "Silo, Secret y Hell.",
                        "communication": "\"Yard listo / flash arriba\"",
                        "onTeammateDeath": "Mantener la presión y apoyar el sitio.",
                        "onNoContact": "Avanzar hacia la planta con cuidado.",
                        "postplant": "Cubrir desde Silo y Heaven.",
                    },
                },
            }
        ],
        "buy": [
            {
                "id": "nuke-buy-a-squeeze",
                "name": "A Squeeze",
                "category": "Full Buy",
                "type": "buy",
                "team": "T",
                "description": "Combinar ramp y squeaky con humo de heaven para forzar el A.",
                "objectivePrincipal": "Abrir A con múltiples líneas de presión.",
                "concept": "Distraer al CT en ramp mientras squeaky entra con utility.",
                "risks": ["AWP en Heaven", "no trade suficiente"],
                "failReaction": "Si A no se abre, retroceder a B con util restante.",
                "adaptationsPossible": "Cambiar a split B.",
                "midRoundOptions": ["Plantar A", "reagruparse"],
                "winCondition": "A con planta segura y cuórum del sitio.",
                "failureStates": ["Squeaky aislado", "AWP en Heaven"],
                "commonMistakes": ["no coordinar smokes", "forzar sin trade"],
                "recoveryPlan": "Cubrir la planta desde Heaven y Hut.",
                "economyLogic": "Invertir en todas las util esenciales.",
                "minimumUtility": ["Smoke Heaven", "Smoke Squeaky", "Flash Ramp"],
                "priorityWeapons": ["Rifle en Squeaky", "AWP en Outside"],
                "spacingRules": "Trade entre ramp y squeaky.",
                "utilityLayering": "Smoke Heaven -> Smoke Squeaky -> Flash Ramp.",
                "timingWindows": "Ejecutar a 22-24s.",
                "reactionTree": "A abierto -> empujar; A contestado -> plantar seguro.",
                "rotationPunish": "Si CT rota lento, plantar con apoyo de Squeaky.",
                "lurkTiming": "El lurker en Vent corta rotación si hay rotaciones a B.",
                "infoProtocols": "Reportar Heaven y Squeaky.",
                "setup": "3 Ramp / 2 Outside.",
                "playerDistribution": "Tres Ramp, dos Outside.",
                "importantSpaces": ["Ramp", "Squeaky", "Heaven"],
                "pointOfContact": "A Site.",
                "postplant": "Cubrir desde Heaven y Hut.",
                "roles": {
                    "support": {
                        "position": "Squeaky",
                        "objective": "Proveer util y trade en el execute A.",
                        "utility": "Smoke Squeaky y flash Ramp.",
                        "timing": "Sincronizar con el avance de Ramp.",
                        "responsibility": "Mantener la presión del sitio y asegurar el trade.",
                        "whatToLook": "Heaven, Hut y Ramp.",
                        "communication": "\"Squeaky listo / A en camino\"",
                        "onTeammateDeath": "Cerrar el hueco y estabilizar el sitio.",
                        "onNoContact": "Apoyar con util y mantener la línea.",
                        "postplant": "Cubrir desde Silo y Secret.",
                    },
                },
            }
        ],
        "midRound": [
            {
                "id": "nuke-midround-backdoor-b",
                "name": "Mid Round Backdoor B",
                "category": "Mid Round",
                "type": "midRound",
                "team": "T",
                "description": "Volver a B por Secret y Yard después de generar dudas en A.",
                "objectivePrincipal": "Aprovechar la rotación CT hacia A para explotar B.",
                "concept": "Fingir el ataque A y cambiar a B con ventaja de rotación.",
                "risks": ["CT mantiene B", "Secret no limpia"],
                "failReaction": "Si Secret está cerrada, girar a A de nuevo.",
                "adaptationsPossible": "Reconvertir en un rush B directo.",
                "midRoundOptions": ["Entrar B", "reagruparse"],
                "winCondition": "B abierto con menos rotaciones en contra.",
                "failureStates": ["B bloqueado"],
                "commonMistakes": ["cambiar sin información", "no limpiar Secret"],
                "recoveryPlan": "Volver a Outside y jugar un split B lento.",
                "economyLogic": "Conservar util para el cambio.",
                "minimumUtility": ["Smoke Yard", "Flash Secret"],
                "priorityWeapons": ["Rifle Secret", "AWP Outside"],
                "spacingRules": "Entrar con trade cercano.",
                "utilityLayering": "Smoke Yard -> Flash Secret.",
                "timingWindows": "Cambiar tras 18-20s.",
                "reactionTree": "B libre -> empujar; B contestado -> reset.",
                "rotationPunish": "Si CT rota mal, explotar la abertura tras A.",
                "lurkTiming": "Lurker en Outside corta la rotación.",
                "infoProtocols": "Reportar A y B simultáneamente.",
                "setup": "2 Outside / 3 Secret.",
                "playerDistribution": "Dos Outside, tres Secret.",
                "importantSpaces": ["Secret", "Yard", "B Site"],
                "pointOfContact": "Yard.",
                "postplant": "Cubrir desde Silo y Heaven.",
                "roles": {
                    "rotator": {
                        "position": "Outside",
                        "objective": "Cortar la rotación hacia B y asegurar el backdoor.",
                        "utility": "Flash Secret y smoke Yard.",
                        "timing": "Entrar tras confirmar el ataque a A.",
                        "responsibility": "Ser la bala extra que llega al sitio B.",
                        "whatToLook": "A, B y rotaciones.",
                        "communication": "\"Backdoor listo / B en camino\"",
                        "onTeammateDeath": "Retirarse a Outside y mantener la línea.",
                        "onNoContact": "Avanzar con precaución hacia Secret.",
                        "postplant": "Cubrir desde Secret y Silo.",
                    },
                },
            }
        ],
    },
}


def js_quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\\"').replace('\n', '\\n') + '"'


def render_value(value: Any, indent: int = 0) -> str:
    spacing = '  ' * indent
    if isinstance(value, str):
        return js_quote(value)
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        if not value:
            return '[]'
        if all(not isinstance(item, (dict, list)) for item in value):
            return '[' + ', '.join(render_value(item) for item in value) + ']'
        return '[\n' + ',\n'.join(spacing + '  ' + render_value(item, indent + 1) for item in value) + '\n' + spacing + ']'
    if isinstance(value, dict):
        return '{\n' + ',\n'.join(spacing + '  ' + f'{key}: {render_value(val, indent + 1)}' for key, val in value.items()) + '\n' + spacing + '}'
    raise TypeError(f'Unsupported type: {type(value)}')


def write_ts(path: Path, name: str, export_type: str, payload: Any) -> None:
    path.write_text(
        f'import type {{ {export_type} }} from "../core/types";\n\nexport const {name}: {export_type} = {render_value(payload)}\n',
        encoding='utf-8',
    )


def write_strat_module(path: Path, name: str, strats: list[dict[str, Any]]) -> None:
    core_import = "../core" if path.parent.name != "strats" else "../../core"
    lines = [
        f'import type {{ StratDetail }} from "{core_import}/types";',
        f'import {{ createStrat, fillRole }} from "{core_import}/stratTemplates";',
        f'import {{ sharedRoles }} from "{core_import}/sharedRoles";',
        '',
        f'export const {name}: StratDetail[] = [',
    ]
    for strat in strats:
        lines.append('  createStrat({')
        for key, value in strat.items():
            if key == 'roles':
                continue
            if key == 'category' and isinstance(value, str):
                value = CATEGORY_MAP.get(value, value)
            lines.append(f'    {key}: {render_value(value, 2)},')
        lines.append('    roles: {')
        for role_name, role_payload in strat.get('roles', {}).items():
            lines.append(
                f'      {role_name}: fillRole({render_value(role_payload, 3)}, sharedRoles.{role_name}),'  # type: ignore
            )
        lines.append('    },')
        lines.append('  }),')
    lines.append('];')
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def write_map_index(map_id: str) -> None:
    folder = MAP_ROOT / map_id
    imports = [
        'import type { MapPlaybook } from "../core/types";',
        f'import {{ {map_id}Philosophy }} from "./philosophy";',
        f'import {{ {map_id}Callouts }} from "./callouts";',
        f'import {{ {map_id}Fundamentals }} from "./fundamentals";',
        f'import {{ {map_id}Defaults }} from "./defaults";',
        f'import {{ {map_id}Protocols }} from "./protocols";',
        f'import {{ {map_id}Retakes }} from "./retakes";',
        f'import {{ {map_id}Reaggressions }} from "./reaggressions";',
        f'import {{ {map_id}AntiEco }} from "./antiEco";',
        f'import {{ {map_id}PistolStrats }} from "./strats/pistol";',
        f'import {{ {map_id}EcoStrats }} from "./strats/eco";',
        f'import {{ {map_id}ForceStrats }} from "./strats/force";',
        f'import {{ {map_id}BuyStrats }} from "./strats/buy";',
        f'import {{ {map_id}MidRoundStrats }} from "./strats/midRound";',
    ]
    body = f"""export const {map_id}Map: MapPlaybook = {{
  id: '{map_id}',
  name: '{MAPS[map_id]['name']}',
  image: '/maps/{map_id}-card.svg',
  calloutImage: '/maps/callout-bg.svg',
  sideFavor: '{MAPS[map_id]['sideFavor']}',
  description: '{MAPS[map_id]['description']}',
  philosophy: {map_id}Philosophy,
  callouts: {map_id}Callouts,
  fundamentals: {map_id}Fundamentals,
  defaults: {map_id}Defaults,
  protocols: {map_id}Protocols,
  retakes: {map_id}Retakes,
  reaggressions: {map_id}Reaggressions,
  antiEco: {map_id}AntiEco,
  strats: {{
    pistol: {map_id}PistolStrats,
    eco: {map_id}EcoStrats,
    force: {map_id}ForceStrats,
    buy: {map_id}BuyStrats,
    midRound: {map_id}MidRoundStrats,
    default: {map_id}Defaults,
    protocol: {map_id}Protocols,
    antiEco: {map_id}AntiEco,
    reaggression: {map_id}Reaggressions,
  }},
}};
"""
    (folder / 'index.ts').write_text('\n'.join(imports) + '\n\n' + body, encoding='utf-8')


def update_maps_index() -> None:
    map_ids = sorted(
        [folder.name for folder in MAP_ROOT.iterdir() if folder.is_dir() and folder.name != 'core' and (folder / 'index.ts').exists()]
    )
    imports = [f'import {{ {map_id}Map }} from "./{map_id}";' for map_id in map_ids]
    exports = ', '.join(f'{map_id}Map' for map_id in map_ids)
    table = [
        'export const allMaps = [' + exports + '];',
        '',
        'export const mapsById = allMaps.reduce((acc, map) => {',
        '  acc[map.id] = map;',
        '  return acc;',
        '}, {} as Record<string, typeof allMaps[number]>);',
        '',
        'export { ' + exports + ' };',
    ]
    (MAP_ROOT / 'index.ts').write_text('\n'.join(imports + [''] + table) + '\n', encoding='utf-8')


def main() -> None:
    MAP_ROOT.mkdir(parents=True, exist_ok=True)
    for map_id, payload in MAPS.items():
        folder = MAP_ROOT / map_id
        strat_folder = folder / 'strats'
        strat_folder.mkdir(parents=True, exist_ok=True)
        folder.mkdir(parents=True, exist_ok=True)

        write_ts(folder / 'philosophy.ts', f'{map_id}Philosophy', 'MapPhilosophy', payload['philosophy'])
        write_ts(folder / 'callouts.ts', f'{map_id}Callouts', 'MapCallouts', payload['callouts'])
        write_ts(folder / 'fundamentals.ts', f'{map_id}Fundamentals', 'MapFundamentals', payload['fundamentals'])

        write_strat_module(folder / 'defaults.ts', f'{map_id}Defaults', payload['defaults'])
        write_strat_module(folder / 'protocols.ts', f'{map_id}Protocols', payload['protocols'])
        write_strat_module(folder / 'retakes.ts', f'{map_id}Retakes', payload['retakes'])
        write_strat_module(folder / 'reaggressions.ts', f'{map_id}Reaggressions', payload['reaggressions'])
        write_strat_module(folder / 'antiEco.ts', f'{map_id}AntiEco', payload['antiEco'])
        write_strat_module(strat_folder / 'pistol.ts', f'{map_id}PistolStrats', payload['pistol'])
        write_strat_module(strat_folder / 'eco.ts', f'{map_id}EcoStrats', payload['eco'])
        write_strat_module(strat_folder / 'force.ts', f'{map_id}ForceStrats', payload['force'])
        write_strat_module(strat_folder / 'buy.ts', f'{map_id}BuyStrats', payload['buy'])
        write_strat_module(strat_folder / 'midRound.ts', f'{map_id}MidRoundStrats', payload['midRound'])

        write_map_index(map_id)

    update_maps_index()


if __name__ == '__main__':
    main()
