import { Tactic } from "@/types";

export const tacticDefault1: Tactic = {
  id: "dust2-default-2-1-2",
  name: "Default 2-1-2",
  category: "Default",
  team: "T",
  setup: "2 Largo / 1 Mid / 2 B",
  description: "Presión dividida para leer la respuesta CT antes de comprometerse.",
  objectivePrincipal: "Obtener información de largo y mid para decidir el sitio.",
  concept: "No gastar util hasta tener lectura; el mid va a ventanas para observar.",
  winCondition: "Llegar a 20s con un pick o información clara del lado débil.",
  failureStates: ["Largo y mid perdidos sin información", "Util gastada sin impacto"],
  commonMistakes: ["Entrar solos a largo", "Mid sin apoyo de flash"],
  minimumUtility: ["Smoke corner largo", "Flash ventanas"],
  priorityWeapons: ["AWP largo", "Rifle mid"],
  timingWindows: "Decidir sitio entre 18-22s.",
  reactionTree: "Pick en largo -> ejecutar A con split corto/mid; Pick en mid -> explotar B con tunnels; Sin pick -> resetear y jugar una segunda ronda de presión.",
  lurkTiming: "El lurker de corto entra a los 20s para cortar rotación CT.",
  postplant: "Cubrir desde Rampa y Pit.",
  roles: [
    {
      name: "entry",
      label: "Entry (Largo)",
      position: "Largo CT",
      objective: "Ganar espacio y forzar que el AWP CT se reubique.",
      utility: "Smoke corner, Flash pocket",
      timing: "Avanzar a 10s, smoke a 12s.",
      responsibility: "Abrir largo con trades; no morirse expuesto.",
      whatToLook: "Corner, CT Spawn, Puerta A",
      communication: "Largo limpio / AWP visto en corner",
      onTeammateDeath: "Retroceder al corner y esperar el segundo trade.",
      onNoContact: "Avanzar al CT Largo y buscar información de corto.",
      postplant: "Cubrir desde Rampa con el rifle.",
    },
    {
      name: "support",
      label: "Support (Mid)",
      position: "Ventanas / Suelo Mid",
      objective: "Observar los movimientos CT y preparar el split.",
      utility: "Flash ventanas, Smoke xbox",
      timing: "Llegar a ventanas a 8s.",
      responsibility: "Proveer información de rotaciones CT.",
      whatToLook: "Catwalk, CT Spawn, Puerta A",
      communication: "CT rotó a B / mid despejado",
      onTeammateDeath: "Cerrar mid y acompañar al grupo que queda.",
      onNoContact: "Mantener la posición en ventanas hasta la decisión de sitio.",
      postplant: "Cubrir desde Xbox o Catwalk.",
    }
  ],
};