import type { RoleDetail } from './types';

export const sharedRoles: Record<string, RoleDetail> = {
  entry: {
    position: 'Entry',
    objective: 'Ganar el primer ángulo y abrir espacio para el equipo.',
    utility: 'Flash de entrada o humo de apoyo según la jugada.',
    timing: 'Inicia el compromiso inmediato tras la confirmación del setup.',
    responsibility: 'Forzar el contacto y absorber el primer fuego enemigo.',
    whatToLook: 'Ángulos cortos, esquinas profundas y posibles rotaciones del defensor.',
    communication: '"Entry listo / contacto incoming"',
    onTeammateDeath: 'No retirarse; avenzar con trade cercano y coordinar con support.',
    onNoContact: 'Reubicarse para un segundo contacto o cerrar la esquina según la llamada.',
    postplant: 'Formar una cruz limpia en el sitio y mantener visión de rotaciones.',
  },
  lurker: {
    position: 'Lurker',
    objective: 'Recibir información, cortar rotaciones y explotar espacios abiertos.',
    utility: 'Smoke o molotov de corte y una flash de escape si es necesario.',
    timing: 'Mantenerse retrasado hasta que el sitio principal se comprometa.',
    responsibility: 'Ser la bala extra que llega al final o aisla información enemiga.',
    whatToLook: 'Rotaciones, flancos y signos de stack enemigo.',
    communication: '"Lurker informa / rotación detectada"',
    onTeammateDeath: 'Cerrar la rotación enemiga y evitar que el bomb sea cortado desde atrás.',
    onNoContact: 'Empujar lentamente para confirmar la ausencia enemiga y crear presión lateral.',
    postplant: 'Posicionarse en un ángulo que cubra la entrada de rotación y el segundo acceso.',
  },
  support: {
    position: 'Support',
    objective: 'Proveer utilidad efectiva y asegurar trades.',
    utility: 'Flashes de seguimiento, smokes de isolación y molotovs de denial.',
    timing: 'Sincronizar util con el entry para evitar que el rival responda primero.',
    responsibility: 'Hacer la jugada viable para el entry y óstructir la defensa enemiga.',
    whatToLook: 'Ángulos enemigos aún vivos y cualquier línea de punish del rival.',
    communication: '"Support listo / flash arriba"',
    onTeammateDeath: 'Proteger el espacio ganado y meter util de retardo si es necesario.',
    onNoContact: 'Usar util para validar el ángulo y dar seguridad antes de avanzar.',
    postplant: 'Sostener el sitio y cortar el retake enemigo con humo o molotov.',
  },
  anchor: {
    position: 'Anchor',
    objective: 'Ser la última barrera en la entrada del sitio y mantener control de la zona.',
    utility: 'Molotovs defensivos y smokes de retraso en caso de retake.',
    timing: 'Asegurar la posición antes del bomb plant y resistir hasta la rotación final.',
    responsibility: 'No ceder el ángulo principal y dar tiempo a la rotación de ayuda.',
    whatToLook: 'Camino principal del site, posibles late pushes y flancos.',
    communication: '"Anchor a punto / necesito rotación"',
    onTeammateDeath: 'Reforzar la posición con util y preparar la defensa en el postplant.',
    onNoContact: 'Mantener el sitio y no aguantarse a peeks prematuros.',
    postplant: 'Establecer cruz con el segundo jugador y usar util de retake defensiva.',
  },
  rotator: {
    position: 'Rotator',
    objective: 'Defender la zona de acceso entre sites y asistir al sitio con velocidad.',
    utility: 'Smoke o flash para ralentizar el avance rival y ganar segundos.',
    timing: 'Esperar información clara antes de comprometerse a una rotación.',
    responsibility: 'Leer la ronda y no rotar sin base de información.',
    whatToLook: 'Contacto enemigo, tiempo del bomb y voces de aliados.',
    communication: '"Rotación disponible / no rotar aún"',
    onTeammateDeath: 'Abandonar el rotador si el sitio se pierde y ayudar a cerrar la ronda.',
    onNoContact: 'Mantenerse fundido en el área de control y extender según el tempo.',
    postplant: 'Aportar un segundo ángulo para el retake o un corte de rotación adversaria.',
  },
  awper: {
    position: 'AWPer',
    objective: 'Ganar el duelo de largo alcance y negar el espacio principal enemigo.',
    utility: 'Flash para tomar un ángulo más seguro y humo de deny si aplica.',
    timing: 'Buscar el pick temprano y luego reubicarse antes del segundo contacto.',
    responsibility: 'Proteger el ángulo largo y evitar que el rival obtenga control del mapa.',
    whatToLook: 'Calls enemigos, pasos largos y ángulos abiertos de rotación.',
    communication: '"AWP listo / cubro largo"',
    onTeammateDeath: 'Retroceder a una posición segura y mantener visión de la zona clave.',
    onNoContact: 'Usar el alcance para curar la ronda y castigar cualquier avance enemigo.',
    postplant: 'Ser el punto de corte de rotaciones y la amenaza de la línea larga.',
  },
  secondEntry: {
    position: 'Second Entry',
    objective: 'Proteger al entry principal y asegurar el trade inmediato.',
    utility: 'Flash de reafirmación o molotov de cubrir línea enemiga.',
    timing: 'Seguir al entry con una ventana corta para evitar exposición temprana.',
    responsibility: 'Asegurar que el primer contacto no quede aislado.',
    whatToLook: 'El cuerpo del entry, líneas de trade y posibles swaps enemigos.',
    communication: '"Siguiente en camino / trade listo"',
    onTeammateDeath: 'Empujar para convertir la presión en control de sitio.',
    onNoContact: 'Mantenerse en la línea de trade y no saltar a posiciones abiertas.',
    postplant: 'Formar la cruz con el entry y mantener visión de los flancos enemigos.',
  },
};
